In [21]:
import pandas as pd

In [22]:
data = pd.read_csv("../backend/dataset/indian_water_physicochemical_parameters.csv", encoding = 'unicode_escape')
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data

,STATION CODE,LOCATIONS,STATE,Temp,D.O. (mg/l),PH,CONDUCTIVITY (Âµmhos/cm),B.O.D. (mg/l),NITRATENAN N+ NITRITENANN (mg/l),FECAL COLIFORM (MPN/100ml),TOTAL COLIFORM (MPN/100ml)Mean,year,date
0,1393.0,DAMANGANGA AT D/S OF MADHUBAN,DAMAN & DIU,31.0,7.1,7.8,151.0,8.0,0.08,233.0,465.0,2012,2012-01-01
1,1150.0,DAMANGANGA AT KACHIGAON U\S AT GIDC WIER,GUJARAT,28.0,7.2,7.4,319.0,0.7,0.18,5.0,10.0,2012,2012-01-04
2,1865.0,RIVER DHADAR AT KOTHADA,GUJARAT,27.0,6.2,8.4,894.0,9.0,0.38,140.0,350.0,2012,2012-01-05
3,1149.0,KOLAK AT PATALIA BDG,GUJARAT,29.0,2.4,7.6,1500.0,6.2,1.31,3.0,13.0,2012,2012-01-06
4,1399.0,ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS,GOA,31.0,5.9,7.2,52.0,2.1,0.08,233.0,90.0,2012,2012-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,2052.0,TUIRIAL UPPER CATCHMENT,MIZORAM,23.6,6.9,7.1,186.0,1.6,0.10,233.0,29.0,2014,2014-12-22
734,2053.0,TUIRIAL LOWER CATCHMENT,MIZORAM,23.5,6.8,7.1,201.0,1.4,0.20,233.0,86.0,2014,2014-12-24
735,1403.0,"GUMTI AT U/S SOUTH TRIPURA,TRIPURA",TRIPURA,27.3,6.2,7.8,165.0,2.1,0.00,282.0,340.0,2014,2014-12-25
736,1404.0,"GUMTI AT D/S SOUTH TRIPURA, TRIPURA",TRIPURA,29.1,6.4,7.8,158.0,4.1,0.50,458.0,500.0,2014,2014-12-26
737,1726.0,"CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA",TRIPURA,26.6,6.6,7.9,210.0,4.2,1.90,510.0,572.0,2014,2014-12-27

In [23]:
temp = data["Temp"].values
print(type(temp[0]))
temp

<class 'numpy.float64'>

array([31. , 28. , 27. , 29. , 31. , 30. , 30. , 29. , 29. , 29. , 28. ,
       30. , 30. , 27. , 28. , 29. , 28. , 29. , 29. , 30. , 28. , 28. ,
       29. , 28. , 30. , 30. , 31. , 29. , 30. , 29. , 29. , 29. , 29. ,
       30. , 27. , 27. , 27. , 23. , 29. , 29. , 29. , 28. , 29. , 29. ,
       29. , 29. , 30. , 30. , 29. , 25. , 30. , 30. , 31. , 30. , 30. ,
       28. , 28. , 28. , 27. , 27. , 26. , 27. , 28. , 23. , 22. , 23. ,
       26. , 26. , 26. , 26. , 26. , 26. , 29. , 28. , 28. , 29. , 26. ,
       26. , 28. , 29. , 26. , 26. , 25. , 29. , 29. , 25. , 27. , 27. ,
       29. , 29. , 29. , 27. , 30. , 27. , 27. , 25. , 25. , 26. , 29. ,
       27. , 27. , 27. , 28. , 26. , 29. , 27. , 28. , 29. , 28. , 29. ,
       26. , 28. , 28. , 28. , 28. , 27. , 28. , 28. , 28. , 28. , 28. ,
       28. , 26. , 28. , 29. , 28. , 26. , 29. , 29. , 27. , 29. , 27. ,
       27. , 20. , 24. , 28. , 27. , 32. , 30. , 22. , 22. , 24. , 27. ,
       26. , 25. , 28. , 26. , 28. , 31. , 25. , 25. , 25. , 27. , 23. ,
       25. , 26. , 29. , 24. , 24. , 29. , 29. , 24. , 29. , 26. , 27. ,
       27. , 21. , 24. , 21. , 24. , 21. , 18. , 22. , 22. , 24. , 22. ,
       22. , 27. , 27. , 27. , 33. , 20. , 20. , 20. , 18. , 24. , 19. ,
       23. , 24. , 23. , 28. , 29. , 30. , 30. , 28. , 29. , 30. , 29. ,
       28. , 28. , 30. , 28. , 29. , 28. , 29. , 32. , 32. , 30. , 29. ,
       31. , 29. , 30. , 29. , 30. , 29. , 29. , 30. , 29. , 29. , 28. ,
       29. , 29. , 30. , 28. , 28. , 29. , 30. , 30. , 25. , 25. , 25. ,
       24. , 17. , 23. , 25. , 25. , 25. , 20. , 22. , 20. , 21. , 17. ,
       17. , 24. , 18. , 18. , 18. , 25. , 19. , 21. , 21. , 18. , 19. ,
       18. , 24. , 17. , 19. , 24. , 22. , 20. , 20. , 24. , 24. , 24. ,
       24. , 28. , 28. , 27. , 27.1, 27.3, 24.5, 27.5, 28.4, 27. , 27.6,
       27. , 27. , 27. , 29. , 27. , 30. , 30.4, 30.8, 30.3, 30.1, 29.9,
       29.1, 29.9, 29.8, 27.9, 28.2, 29.6, 28.8, 29.5, 29.8, 29.7, 28.7,
       27.9, 29.3, 28.6, 29.8, 28.6, 30.6, 30.3, 30.4, 29.6, 29.6, 29.5,
       26.7, 29.3, 28. , 28.2, 26.5, 20.7, 27.2, 27.5, 26. , 26.5, 27. ,
       27.3, 28.7, 28.4, 28.7, 28.7, 28.7, 28.7, 28.7, 29.3, 28.3, 28.7,
       29.2, 28.7, 27.2, 27.2, 27.2, 28. , 26.2, 26.2, 28.2, 24.5, 24.5,
       24.5, 24. , 24.9, 24.3, 24.8, 26.4, 27. , 26.6, 28.6, 28.8, 28. ,
       27.4, 27.5, 26.8, 30. , 28.8, 27.4, 24.8, 23.6, 29.8, 30.2, 28.2,
       27.7, 23.9, 27.8, 26.4, 29.6, 27. , 26.3, 30. , 28. , 30.1, 27.9,
       27. , 26. , 27.7, 27.1, 26.5, 28.5, 28.7, 25.7, 29.3, 27. , 27.1,
       30.3, 30.4, 26.2, 26.2, 25.1, 27.4, 28.1, 28.3, 28.2, 27.2, 27.4,
       28.2, 27.9, 27.3, 28.2, 28.2, 26.7, 28. , 29.7, 28.9, 26.4, 30. ,
       27.8, 26.7, 27. , 26.8, 19. , 21.4, 27.1, 26.3, 28.3, 27.9, 23.4,
       23.5, 22.4, 26.8, 26.5, 22. , 27.6, 25.6, 26.5, 24. , 28. , 28. ,
       28. , 27. , 27.8, 23.4, 25.4, 26.3, 29. , 24.6, 23.5, 29. , 27. ,
       24. , 28.7, 26.3, 25.7, 27. , 23.3, 22.8, 23.3, 21.8, 24.3, 23.5,
       24. , 23.5, 23.3, 22.5, 26. , 25.8, 27. , 27. , 27. , 27. , 30.7,
       20.3, 20.7, 20.8, 20.6, 28. , 23.4, 25.3, 31.1, 26.3, 22. , 24.4,
       23.7, 24.6, 23.1, 18.2, 18.8, 23.8, 17.8, 18.7, 18.8, 22.6, 25.2,
       24.8, 19.9, 20.7, 20.6, 21.5, 17.7, 17.9, 23.9, 18. , 18.4, 18.8,
       24.8, 19.3, 20.6, 20.7, 17.6, 22.7, 17.9, 19.4, 23.7, 22.7, 23.6,
       23.8, 23.5, 23.5, 27.4, 21.9, 27.5, 30.6, 29.8, 29.5, 29.7, 29.5,
       30. , 29.2, 29.6, 30. , 30.1, 27.8, 27.9, 29.3, 29.2, 30. , 29. ,
       29.1, 28.7, 28.7, 29.5, 29. , 29.4, 30.1, 30.3, 30.5, 29.1, 30.1,
       29.2, 25.1, 29.6, 27.4, 27.8, 30.6, 25. , 25. , 25. , 25.1, 26.1,
       21.4, 27.4, 27.1, 27.2, 27.3, 27. , 27.2, 27. , 22.6, 28.4, 28. ,
       27.6, 27.9, 28.1, 27.1, 27.6, 27.3, 27.8, 28. , 28.1, 28.6, 26.9,
       23. , 23. , 23. , 25.1, 24.6, 25.7, 24.8, 27.3, 27.5, 25.2, 29.9,
       29.8, 27.8, 26.7, 25.8, 26.4, 29.8, 28.6, 26.9, 26. , 23.6, 30.3,
       30.7, 28.2, 24.8, 29.2, 26.6, 30.4, 25.1, 28.9, 28.8, 29.3, 29.5,
       28.4, 26.9, 25.8, 26.6, 25.3, 28.2, 28.5, 27.6, 29. , 27.5, 27.8,
       30.2, 25.3, 25.3, 25.8, 27.2, 28.1, 28.3, 28.1, 27.7, 28. , 28.2,
       28. , 28.1, 28.1, 28.1, 27.3, 28.3, 29.1, 28.7, 28.5, 26.6, 31. ,
       28.8, 25.3, 25.9, 26.5, 18.9, 20.5, 27.1, 26.3, 29.1, 28.4, 24.7,
       24.4, 22.7, 24.8, 24. , 22.8, 26.8, 25.3, 27.1, 29. , 32. , 29.3,
       22.8, 24.5, 25.5, 29. , 23.8, 22.8, 29. , 29. , 23. , 29. , 25.7,
       25.7, 27. , 22.7, 19. , 23. , 24. , 24.7, 25. , 22. , 24.3, 23.3,
       19.5, 21.5, 20. , 27. , 27. , 32.6, 23.6, 23.9, 24.5, 27. , 18.1,
       25.1, 22.3, 23.7, 23.9, 25.5, 25.1, 25.2, 23.2, 18.3, 19.3, 24. ,
       21.2, 26.3, 25.5, 20. , 20.3, 19.4, 21. , 19.2, 18.3, 19.6, 23.7,
       18.2, 18.8, 18.9, 25.1, 18.8, 20.2, 20. , 18.8, 18.2, 22.1, 17.6,
       18.7, 23.1, 22.6, 20. , 19.9, 24.5, 24.4, 23.6, 23.5, 27.3, 29.1,
       26.6])

In [24]:
dates = data["date"].values
print(type(dates[0]))
dates

<class 'str'>

array(['2012-01-01', '2012-01-04', '2012-01-05', '2012-01-06',
       '2012-01-07', '2012-01-10', '2012-01-13', '2012-01-15',
       '2012-01-16', '2012-01-17', '2012-01-18', '2012-01-20',
       '2012-01-22', '2012-01-23', '2012-01-26', '2012-01-27',
       '2012-01-28', '2012-02-02', '2012-02-04', '2012-02-05',
       '2012-02-06', '2012-02-10', '2012-02-11', '2012-02-12',
       '2012-02-13', '2012-02-15', '2012-02-16', '2012-02-18',
       '2012-02-19', '2012-02-20', '2012-02-21', '2012-02-22',
       '2012-02-24', '2012-02-25', '2012-02-27', '2012-03-01',
       '2012-03-02', '2012-03-03', '2012-03-04', '2012-03-05',
       '2012-03-06', '2012-03-07', '2012-03-08', '2012-03-09',
       '2012-03-10', '2012-03-11', '2012-03-12', '2012-03-14',
       '2012-03-16', '2012-03-17', '2012-03-18', '2012-03-19',
       '2012-03-20', '2012-03-22', '2012-03-23', '2012-03-24',
       '2012-03-26', '2012-03-27', '2012-03-28', '2012-04-01',
       '2012-04-02', '2012-04-04', '2012-04-05', '2012-04-06',
       '2012-04-07', '2012-04-09', '2012-04-10', '2012-04-11',
       '2012-04-12', '2012-04-13', '2012-04-14', '2012-04-15',
       '2012-04-16', '2012-04-17', '2012-04-18', '2012-04-19',
       '2012-04-20', '2012-04-21', '2012-04-22', '2012-04-23',
       '2012-04-24', '2012-04-25', '2012-04-26', '2012-04-27',
       '2012-04-28', '2012-05-01', '2012-05-02', '2012-05-03',
       '2012-05-04', '2012-05-05', '2012-05-06', '2012-05-07',
       '2012-05-08', '2012-05-10', '2012-05-12', '2012-05-13',
       '2012-05-14', '2012-05-15', '2012-05-16', '2012-05-17',
       '2012-05-18', '2012-05-19', '2012-05-22', '2012-05-23',
       '2012-05-24', '2012-05-25', '2012-05-27', '2012-05-28',
       '2012-06-01', '2012-06-02', '2012-06-03', '2012-06-04',
       '2012-06-05', '2012-06-06', '2012-06-07', '2012-06-08',
       '2012-06-09', '2012-06-10', '2012-06-11', '2012-06-12',
       '2012-06-14', '2012-06-15', '2012-06-16', '2012-06-17',
       '2012-06-18', '2012-06-19', '2012-06-20', '2012-06-21',
       '2012-06-22', '2012-06-24', '2012-06-25', '2012-06-27',
       '2012-06-28', '2012-07-01', '2012-07-03', '2012-07-04',
       '2012-07-05', '2012-07-07', '2012-07-08', '2012-07-09',
       '2012-07-10', '2012-07-11', '2012-07-12', '2012-07-14',
       '2012-07-15', '2012-07-16', '2012-07-17', '2012-07-18',
       '2012-07-19', '2012-07-20', '2012-07-21', '2012-07-23',
       '2012-07-24', '2012-07-25', '2012-07-26', '2012-07-27',
       '2012-07-28', '2012-08-01', '2012-08-03', '2012-08-04',
       '2012-08-05', '2012-08-06', '2012-08-07', '2012-08-08',
       '2012-08-10', '2012-08-11', '2012-08-12', '2012-08-13',
       '2012-08-14', '2012-08-15', '2012-08-16', '2012-08-17',
       '2012-08-18', '2012-08-19', '2012-08-20', '2012-08-21',
       '2012-08-22', '2012-08-23', '2012-08-24', '2012-08-25',
       '2012-08-26', '2012-08-27', '2012-08-28', '2012-09-01',
       '2012-09-02', '2012-09-03', '2012-09-04', '2012-09-05',
       '2012-09-06', '2012-09-07', '2012-09-08', '2012-09-09',
       '2012-09-11', '2012-09-13', '2012-09-15', '2012-09-16',
       '2012-09-17', '2012-09-18', '2012-09-19', '2012-09-20',
       '2012-09-21', '2012-09-24', '2012-09-26', '2012-09-27',
       '2012-09-28', '2012-10-01', '2012-10-04', '2012-10-05',
       '2012-10-06', '2012-10-08', '2012-10-10', '2012-10-11',
       '2012-10-12', '2012-10-15', '2012-10-16', '2012-10-17',
       '2012-10-18', '2012-10-19', '2012-10-22', '2012-10-24',
       '2012-10-25', '2012-10-28', '2012-11-01', '2012-11-02',
       '2012-11-03', '2012-11-04', '2012-11-05', '2012-11-06',
       '2012-11-07', '2012-11-08', '2012-11-09', '2012-11-10',
       '2012-11-13', '2012-11-14', '2012-11-16', '2012-11-19',
       '2012-11-20', '2012-11-21', '2012-11-22', '2012-11-23',
       '2012-11-24', '2012-11-25', '2012-11-26', '2012-11-27',
       '2012-11-28', '2012-12-01', '2012-12-02', '2012-12-03',
       '2012-12-04', '2012-12-05', '2012-12-06', '2012-12-07',
       '2012-12-08', '2012-12-09', '2012-12-10', '2012-12-11',
       '2012-12-12', '2012-12-15', '2012-12-17', '2012-12-18',
       '2012-12-19', '2012-12-20', '2012-12-21', '2012-12-22',
       '2012-12-23', '2012-12-24', '2012-12-25', '2012-12-27',
       '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-05',
       '2013-01-07', '2013-01-08', '2013-01-09', '2013-01-11',
       '2013-01-12', '2013-01-13', '2013-01-15', '2013-01-16',
       '2013-01-17', '2013-01-18', '2013-01-20', '2013-01-21',
       '2013-01-22', '2013-01-25', '2013-01-26', '2013-01-27',
       '2013-02-01', '2013-02-02', '2013-02-06', '2013-02-07',
       '2013-02-08', '2013-02-10', '2013-02-12', '2013-02-13',
       '2013-02-14', '2013-02-15', '2013-02-17', '2013-02-18',
       '2013-02-20', '2013-02-21', '2013-02-22', '2013-02-23',
       '2013-02-24', '2013-02-25', '2013-02-26', '2013-02-27',
       '2013-02-28', '2013-03-01', '2013-03-02', '2013-03-04',
       '2013-03-05', '2013-03-06', '2013-03-07', '2013-03-09',
       '2013-03-10', '2013-03-11', '2013-03-12', '2013-03-13',
       '2013-03-14', '2013-03-16', '2013-03-17', '2013-03-18',
       '2013-03-20', '2013-03-21', '2013-03-22', '2013-03-23',
       '2013-03-24', '2013-03-25', '2013-03-27', '2013-03-28',
       '2013-04-01', '2013-04-03', '2013-04-04', '2013-04-05',
       '2013-04-08', '2013-04-09', '2013-04-10', '2013-04-11',
       '2013-04-12', '2013-04-13', '2013-04-15', '2013-04-16',
       '2013-04-17', '2013-04-19', '2013-04-20', '2013-04-21',
       '2013-04-24', '2013-04-25', '2013-04-26', '2013-04-27',
       '2013-05-01', '2013-05-06', '2013-05-07', '2013-05-08',
       '2013-05-09', '2013-05-10', '2013-05-12', '2013-05-13',
       '2013-05-16', '2013-05-17', '2013-05-19', '2013-05-21',
       '2013-05-22', '2013-05-23', '2013-05-24', '2013-05-25',
       '2013-05-27', '2013-06-01', '2013-06-03', '2013-06-04',
       '2013-06-05', '2013-06-06', '2013-06-07', '2013-06-08',
       '2013-06-09', '2013-06-11', '2013-06-13', '2013-06-14',
       '2013-06-15', '2013-06-17', '2013-06-18', '2013-06-19',
       '2013-06-20', '2013-06-21', '2013-06-22', '2013-06-23',
       '2013-06-24', '2013-06-27', '2013-07-01', '2013-07-02',
       '2013-07-04', '2013-07-05', '2013-07-07', '2013-07-09',
       '2013-07-10', '2013-07-11', '2013-07-13', '2013-07-16',
       '2013-07-17', '2013-07-19', '2013-07-20', '2013-07-21',
       '2013-07-23', '2013-07-24', '2013-07-25', '2013-07-27',
       '2013-07-28', '2013-08-01', '2013-08-02', '2013-08-04',
       '2013-08-05', '2013-08-06', '2013-08-08', '2013-08-09',
       '2013-08-12', '2013-08-13', '2013-08-15', '2013-08-18',
       '2013-08-19', '2013-08-20', '2013-08-21', '2013-08-23',
       '2013-08-25', '2013-08-26', '2013-08-27', '2013-08-28',
       '2013-09-01', '2013-09-02', '2013-09-03', '2013-09-04',
       '2013-09-06', '2013-09-07', '2013-09-09', '2013-09-10',
       '2013-09-11', '2013-09-13', '2013-09-14', '2013-09-15',
       '2013-09-17', '2013-09-18', '2013-09-19', '2013-09-20',
       '2013-09-21', '2013-09-22', '2013-09-23', '2013-09-24',
       '2013-09-26', '2013-09-28', '2013-10-01', '2013-10-03',
       '2013-10-04', '2013-10-06', '2013-10-07', '2013-10-08',
       '2013-10-10', '2013-10-11', '2013-10-12', '2013-10-13',
       '2013-10-14', '2013-10-15', '2013-10-16', '2013-10-17',
       '2013-10-18', '2013-10-19', '2013-10-20', '2013-10-21',
       '2013-10-24', '2013-10-25', '2013-10-26', '2013-10-27',
       '2013-11-01', '2013-11-02', '2013-11-04', '2013-11-05',
       '2013-11-07', '2013-11-08', '2013-11-09', '2013-11-10',
       '2013-11-11', '2013-11-13', '2013-11-14', '2013-11-17',
       '2013-11-18', '2013-11-20', '2013-11-22', '2013-11-24',
       '2013-11-25', '2013-11-26', '2013-11-27', '2013-11-28',
       '2013-12-02', '2013-12-03', '2013-12-04', '2013-12-06',
       '2013-12-07', '2013-12-08', '2013-12-09', '2013-12-12',
       '2013-12-13', '2013-12-15', '2013-12-16', '2013-12-18',
       '2013-12-19', '2013-12-20', '2013-12-21', '2013-12-22',
       '2013-12-23', '2013-12-25', '2013-12-26', '2013-12-28',
       '2014-01-02', '2014-01-03', '2014-01-04', '2014-01-05',
       '2014-01-06', '2014-01-07', '2014-01-08', '2014-01-10',
       '2014-01-12', '2014-01-13', '2014-01-14', '2014-01-15',
       '2014-01-17', '2014-01-21', '2014-01-23', '2014-01-28',
       '2014-02-01', '2014-02-02', '2014-02-03', '2014-02-04',
       '2014-02-06', '2014-02-07', '2014-02-08', '2014-02-09',
       '2014-02-14', '2014-02-17', '2014-02-18', '2014-02-19',
       '2014-02-20', '2014-02-23', '2014-02-24', '2014-02-25',
       '2014-02-26', '2014-03-01', '2014-03-02', '2014-03-03',
       '2014-03-04', '2014-03-05', '2014-03-08', '2014-03-09',
       '2014-03-10', '2014-03-12', '2014-03-15', '2014-03-16',
       '2014-03-18', '2014-03-20', '2014-03-22', '2014-03-24',
       '2014-03-25', '2014-03-26', '2014-03-28', '2014-04-02',
       '2014-04-03', '2014-04-04', '2014-04-05', '2014-04-07',
       '2014-04-09', '2014-04-11', '2014-04-12', '2014-04-13',
       '2014-04-14', '2014-04-15', '2014-04-16', '2014-04-17',
       '2014-04-18', '2014-04-19', '2014-04-20', '2014-04-21',
       '2014-04-22', '2014-04-23', '2014-04-25', '2014-04-28',
       '2014-05-02', '2014-05-03', '2014-05-04', '2014-05-05',
       '2014-05-06', '2014-05-08', '2014-05-11', '2014-05-12',
       '2014-05-13', '2014-05-14', '2014-05-15', '2014-05-16',
       '2014-05-17', '2014-05-18', '2014-05-20', '2014-05-21',
       '2014-05-24', '2014-05-25', '2014-05-26', '2014-06-01',
       '2014-06-02', '2014-06-03', '2014-06-05', '2014-06-06',
       '2014-06-07', '2014-06-08', '2014-06-09', '2014-06-10',
       '2014-06-11', '2014-06-12', '2014-06-13', '2014-06-15',
       '2014-06-16', '2014-06-19', '2014-06-20', '2014-06-22',
       '2014-06-23', '2014-06-27', '2014-06-28', '2014-07-01',
       '2014-07-04', '2014-07-06', '2014-07-07', '2014-07-08',
       '2014-07-09', '2014-07-13', '2014-07-14', '2014-07-15',
       '2014-07-16', '2014-07-17', '2014-07-18', '2014-07-21',
       '2014-07-23', '2014-07-24', '2014-07-25', '2014-07-26',
       '2014-07-27', '2014-08-02', '2014-08-04', '2014-08-05',
       '2014-08-08', '2014-08-09', '2014-08-10', '2014-08-11',
       '2014-08-12', '2014-08-13', '2014-08-15', '2014-08-18',
       '2014-08-19', '2014-08-21', '2014-08-22', '2014-08-23',
       '2014-08-25', '2014-08-27', '2014-08-28', '2014-09-01',
       '2014-09-02', '2014-09-03', '2014-09-04', '2014-09-05',
       '2014-09-06', '2014-09-07', '2014-09-09', '2014-09-10',
       '2014-09-11', '2014-09-12', '2014-09-13', '2014-09-14',
       '2014-09-15', '2014-09-16', '2014-09-17', '2014-09-18',
       '2014-09-20', '2014-09-22', '2014-09-23', '2014-09-26',
       '2014-09-27', '2014-09-28', '2014-10-01', '2014-10-02',
       '2014-10-03', '2014-10-04', '2014-10-05', '2014-10-06',
       '2014-10-08', '2014-10-09', '2014-10-11', '2014-10-12',
       '2014-10-13', '2014-10-15', '2014-10-16', '2014-10-21',
       '2014-10-22', '2014-10-23', '2014-10-25', '2014-11-01',
       '2014-11-02', '2014-11-03', '2014-11-05', '2014-11-06',
       '2014-11-07', '2014-11-08', '2014-11-09', '2014-11-10',
       '2014-11-11', '2014-11-14', '2014-11-15', '2014-11-16',
       '2014-11-17', '2014-11-18', '2014-11-19', '2014-11-21',
       '2014-11-23', '2014-11-24', '2014-11-25', '2014-11-27',
       '2014-12-01', '2014-12-02', '2014-12-03', '2014-12-04',
       '2014-12-06', '2014-12-07', '2014-12-12', '2014-12-13',
       '2014-12-14', '2014-12-16', '2014-12-17', '2014-12-18',
       '2014-12-21', '2014-12-22', '2014-12-24', '2014-12-25',
       '2014-12-26', '2014-12-27'], dtype=object)

In [25]:
dict_ = dict(zip(dates, data["Temp"].values))

In [26]:
dict_

{'2012-01-01': 31.0,
 '2012-01-04': 28.0,
 '2012-01-05': 27.0,
 '2012-01-06': 29.0,
 '2012-01-07': 31.0,
 '2012-01-10': 30.0,
 '2012-01-13': 30.0,
 '2012-01-15': 29.0,
 '2012-01-16': 29.0,
 '2012-01-17': 29.0,
 '2012-01-18': 28.0,
 '2012-01-20': 30.0,
 '2012-01-22': 30.0,
 '2012-01-23': 27.0,
 '2012-01-26': 28.0,
 '2012-01-27': 29.0,
 '2012-01-28': 28.0,
 '2012-02-02': 29.0,
 '2012-02-04': 29.0,
 '2012-02-05': 30.0,
 '2012-02-06': 28.0,
 '2012-02-10': 28.0,
 '2012-02-11': 29.0,
 '2012-02-12': 28.0,
 '2012-02-13': 30.0,
 '2012-02-15': 30.0,
 '2012-02-16': 31.0,
 '2012-02-18': 29.0,
 '2012-02-19': 30.0,
 '2012-02-20': 29.0,
 '2012-02-21': 29.0,
 '2012-02-22': 29.0,
 '2012-02-24': 29.0,
 '2012-02-25': 30.0,
 '2012-02-27': 27.0,
 '2012-03-01': 27.0,
 '2012-03-02': 27.0,
 '2012-03-03': 23.0,
 '2012-03-04': 29.0,
 '2012-03-05': 29.0,
 '2012-03-06': 29.0,
 '2012-03-07': 28.0,
 '2012-03-08': 29.0,
 '2012-03-09': 29.0,
 '2012-03-10': 29.0,
 '2012-03-11': 29.0,
 '2012-03-12': 30.0,
 '2012-03-14': 30.0,
 '2012-03-16': 29.0,
 '2012-03-17': 25.0,
 '2012-03-18': 30.0,
 '2012-03-19': 30.0,
 '2012-03-20': 31.0,
 '2012-03-22': 30.0,
 '2012-03-23': 30.0,
 '2012-03-24': 28.0,
 '2012-03-26': 28.0,
 '2012-03-27': 28.0,
 '2012-03-28': 27.0,
 '2012-04-01': 27.0,
 '2012-04-02': 26.0,
 '2012-04-04': 27.0,
 '2012-04-05': 28.0,
 '2012-04-06': 23.0,
 '2012-04-07': 22.0,
 '2012-04-09': 23.0,
 '2012-04-10': 26.0,
 '2012-04-11': 26.0,
 '2012-04-12': 26.0,
 '2012-04-13': 26.0,
 '2012-04-14': 26.0,
 '2012-04-15': 26.0,
 '2012-04-16': 29.0,
 '2012-04-17': 28.0,
 '2012-04-18': 28.0,
 '2012-04-19': 29.0,
 '2012-04-20': 26.0,
 '2012-04-21': 26.0,
 '2012-04-22': 28.0,
 '2012-04-23': 29.0,
 '2012-04-24': 26.0,
 '2012-04-25': 26.0,
 '2012-04-26': 25.0,
 '2012-04-27': 29.0,
 '2012-04-28': 29.0,
 '2012-05-01': 25.0,
 '2012-05-02': 27.0,
 '2012-05-03': 27.0,
 '2012-05-04': 29.0,
 '2012-05-05': 29.0,
 '2012-05-06': 29.0,
 '2012-05-07': 27.0,
 '2012-05-08': 30.0,
 '2012-05-10': 27.0,
 '2012-05-12': 27.0,
 '2012-05-13': 25.0,
 '2012-05-14': 25.0,
 '2012-05-15': 26.0,
 '2012-05-16': 29.0,
 '2012-05-17': 27.0,
 '2012-05-18': 27.0,
 '2012-05-19': 27.0,
 '2012-05-22': 28.0,
 '2012-05-23': 26.0,
 '2012-05-24': 29.0,
 '2012-05-25': 27.0,
 '2012-05-27': 28.0,
 '2012-05-28': 29.0,
 '2012-06-01': 28.0,
 '2012-06-02': 29.0,
 '2012-06-03': 26.0,
 '2012-06-04': 28.0,
 '2012-06-05': 28.0,
 '2012-06-06': 28.0,
 '2012-06-07': 28.0,
 '2012-06-08': 27.0,
 '2012-06-09': 28.0,
 '2012-06-10': 28.0,
 '2012-06-11': 28.0,
 '2012-06-12': 28.0,
 '2012-06-14': 28.0,
 '2012-06-15': 28.0,
 '2012-06-16': 26.0,
 '2012-06-17': 28.0,
 '2012-06-18': 29.0,
 '2012-06-19': 28.0,
 '2012-06-20': 26.0,
 '2012-06-21': 29.0,
 '2012-06-22': 29.0,
 '2012-06-24': 27.0,
 '2012-06-25': 29.0,
 '2012-06-27': 27.0,
 '2012-06-28': 27.0,
 '2012-07-01': 20.0,
 '2012-07-03': 24.0,
 '2012-07-04': 28.0,
 '2012-07-05': 27.0,
 '2012-07-07': 32.0,
 '2012-07-08': 30.0,
 '2012-07-09': 22.0,
 '2012-07-10': 22.0,
 '2012-07-11': 24.0,
 '2012-07-12': 27.0,
 '2012-07-14': 26.0,
 '2012-07-15': 25.0,
 '2012-07-16': 28.0,
 '2012-07-17': 26.0,
 '2012-07-18': 28.0,
 '2012-07-19': 31.0,
 '2012-07-20': 25.0,
 '2012-07-21': 25.0,
 '2012-07-23': 25.0,
 '2012-07-24': 27.0,
 '2012-07-25': 23.0,
 '2012-07-26': 25.0,
 '2012-07-27': 26.0,
 '2012-07-28': 29.0,
 '2012-08-01': 24.0,
 '2012-08-03': 24.0,
 '2012-08-04': 29.0,
 '2012-08-05': 29.0,
 '2012-08-06': 24.0,
 '2012-08-07': 29.0,
 '2012-08-08': 26.0,
 '2012-08-10': 27.0,
 '2012-08-11': 27.0,
 '2012-08-12': 21.0,
 '2012-08-13': 24.0,
 '2012-08-14': 21.0,
 '2012-08-15': 24.0,
 '2012-08-16': 21.0,
 '2012-08-17': 18.0,
 '2012-08-18': 22.0,
 '2012-08-19': 22.0,
 '2012-08-20': 24.0,
 '2012-08-21': 22.0,
 '2012-08-22': 22.0,
 '2012-08-23': 27.0,
 '2012-08-24': 27.0,
 '2012-08-25': 27.0,
 '2012-08-26': 33.0,
 '2012-08-27': 20.0,
 '2012-08-28': 20.0,
 '2012-09-01': 20.0,
 '2012-09-02': 18.0,
 '2012-09-03': 24.0,
 '2012-09-04': 19.0,
 '2012-09-05': 23.0,
 '2012-09-06': 24.0,
 '2012-09-07': 23.0,
 '2012-09-08': 28.0,
 '2012-09-09': 29.0,
 '2012-09-11': 30.0,
 '2012-09-13': 30.0,
 '2012-09-15': 28.0,
 '2012-09-16': 29.0,
 '2012-09-17': 30.0,
 '2012-09-18': 29.0,
 '2012-09-19': 28.0,
 '2012-09-20': 28.0,
 '2012-09-21': 30.0,
 '2012-09-24': 28.0,
 '2012-09-26': 29.0,
 '2012-09-27': 28.0,
 '2012-09-28': 29.0,
 '2012-10-01': 32.0,
 '2012-10-04': 32.0,
 '2012-10-05': 30.0,
 '2012-10-06': 29.0,
 '2012-10-08': 31.0,
 '2012-10-10': 29.0,
 '2012-10-11': 30.0,
 '2012-10-12': 29.0,
 '2012-10-15': 30.0,
 '2012-10-16': 29.0,
 '2012-10-17': 29.0,
 '2012-10-18': 30.0,
 '2012-10-19': 29.0,
 '2012-10-22': 29.0,
 '2012-10-24': 28.0,
 '2012-10-25': 29.0,
 '2012-10-28': 29.0,
 '2012-11-01': 30.0,
 '2012-11-02': 28.0,
 '2012-11-03': 28.0,
 '2012-11-04': 29.0,
 '2012-11-05': 30.0,
 '2012-11-06': 30.0,
 '2012-11-07': 25.0,
 '2012-11-08': 25.0,
 '2012-11-09': 25.0,
 '2012-11-10': 24.0,
 '2012-11-13': 17.0,
 '2012-11-14': 23.0,
 '2012-11-16': 25.0,
 '2012-11-19': 25.0,
 '2012-11-20': 25.0,
 '2012-11-21': 20.0,
 '2012-11-22': 22.0,
 '2012-11-23': 20.0,
 '2012-11-24': 21.0,
 '2012-11-25': 17.0,
 '2012-11-26': 17.0,
 '2012-11-27': 24.0,
 '2012-11-28': 18.0,
 '2012-12-01': 18.0,
 '2012-12-02': 18.0,
 '2012-12-03': 25.0,
 '2012-12-04': 19.0,
 '2012-12-05': 21.0,
 '2012-12-06': 21.0,
 '2012-12-07': 18.0,
 '2012-12-08': 19.0,
 '2012-12-09': 18.0,
 '2012-12-10': 24.0,
 '2012-12-11': 17.0,
 '2012-12-12': 19.0,
 '2012-12-15': 24.0,
 '2012-12-17': 22.0,
 '2012-12-18': 20.0,
 '2012-12-19': 20.0,
 '2012-12-20': 24.0,
 '2012-12-21': 24.0,
 '2012-12-22': 24.0,
 '2012-12-23': 24.0,
 '2012-12-24': 28.0,
 '2012-12-25': 28.0,
 '2012-12-27': 27.0,
 '2013-01-01': 27.1,
 '2013-01-02': 27.3,
 '2013-01-03': 24.5,
 '2013-01-05': 27.5,
 '2013-01-07': 28.4,
 '2013-01-08': 27.0,
 '2013-01-09': 27.6,
 '2013-01-11': 27.0,
 '2013-01-12': 27.0,
 '2013-01-13': 27.0,
 '2013-01-15': 29.0,
 '2013-01-16': 27.0,
 '2013-01-17': 30.0,
 '2013-01-18': 30.4,
 '2013-01-20': 30.8,
 '2013-01-21': 30.3,
 '2013-01-22': 30.1,
 '2013-01-25': 29.9,
 '2013-01-26': 29.1,
 '2013-01-27': 29.9,
 '2013-02-01': 29.8,
 '2013-02-02': 27.9,
 '2013-02-06': 28.2,
 '2013-02-07': 29.6,
 '2013-02-08': 28.8,
 '2013-02-10': 29.5,
 '2013-02-12': 29.8,
 '2013-02-13': 29.7,
 '2013-02-14': 28.7,
 '2013-02-15': 27.9,
 '2013-02-17': 29.3,
 '2013-02-18': 28.6,
 '2013-02-20': 29.8,
 '2013-02-21': 28.6,
 '2013-02-22': 30.6,
 '2013-02-23': 30.3,
 '2013-02-24': 30.4,
 '2013-02-25': 29.6,
 '2013-02-26': 29.6,
 '2013-02-27': 29.5,
 '2013-02-28': 26.7,
 '2013-03-01': 29.3,
 '2013-03-02': 28.0,
 '2013-03-04': 28.2,
 '2013-03-05': 26.5,
 '2013-03-06': 20.7,
 '2013-03-07': 27.2,
 '2013-03-09': 27.5,
 '2013-03-10': 26.0,
 '2013-03-11': 26.5,
 '2013-03-12': 27.0,
 '2013-03-13': 27.3,
 '2013-03-14': 28.7,
 '2013-03-16': 28.4,
 '2013-03-17': 28.7,
 '2013-03-18': 28.7,
 '2013-03-20': 28.7,
 '2013-03-21': 28.7,
 '2013-03-22': 28.7,
 '2013-03-23': 29.3,
 '2013-03-24': 28.3,
 '2013-03-25': 28.7,
 '2013-03-27': 29.2,
 '2013-03-28': 28.7,
 '2013-04-01': 27.2,
 '2013-04-03': 27.2,
 '2013-04-04': 27.2,
 '2013-04-05': 28.0,
 '2013-04-08': 26.2,
 '2013-04-09': 26.2,
 '2013-04-10': 28.2,
 '2013-04-11': 24.5,
 '2013-04-12': 24.5,
 '2013-04-13': 24.5,
 '2013-04-15': 24.0,
 '2013-04-16': 24.9,
 '2013-04-17': 24.3,
 '2013-04-19': 24.8,
 '2013-04-20': 26.4,
 '2013-04-21': 27.0,
 '2013-04-24': 26.6,
 '2013-04-25': 28.6,
 '2013-04-26': 28.8,
 '2013-04-27': 28.0,
 '2013-05-01': 27.4,
 '2013-05-06': 27.5,
 '2013-05-07': 26.8,
 '2013-05-08': 30.0,
 '2013-05-09': 28.8,
 '2013-05-10': 27.4,
 '2013-05-12': 24.8,
 '2013-05-13': 23.6,
 '2013-05-16': 29.8,
 '2013-05-17': 30.2,
 '2013-05-19': 28.2,
 '2013-05-21': 27.7,
 '2013-05-22': 23.9,
 '2013-05-23': 27.8,
 '2013-05-24': 26.4,
 '2013-05-25': 29.6,
 '2013-05-27': 27.0,
 '2013-06-01': 26.3,
 '2013-06-03': 30.0,
 '2013-06-04': 28.0,
 '2013-06-05': 30.1,
 '2013-06-06': 27.9,
 '2013-06-07': 27.0,
 '2013-06-08': 26.0,
 '2013-06-09': 27.7,
 '2013-06-11': 27.1,
 '2013-06-13': 26.5,
 '2013-06-14': 28.5,
 '2013-06-15': 28.7,
 '2013-06-17': 25.7,
 '2013-06-18': 29.3,
 '2013-06-19': 27.0,
 '2013-06-20': 27.1,
 '2013-06-21': 30.3,
 '2013-06-22': 30.4,
 '2013-06-23': 26.2,
 '2013-06-24': 26.2,
 '2013-06-27': 25.1,
 '2013-07-01': 27.4,
 '2013-07-02': 28.1,
 '2013-07-04': 28.3,
 '2013-07-05': 28.2,
 '2013-07-07': 27.2,
 '2013-07-09': 27.4,
 '2013-07-10': 28.2,
 '2013-07-11': 27.9,
 '2013-07-13': 27.3,
 '2013-07-16': 28.2,
 '2013-07-17': 28.2,
 '2013-07-19': 26.7,
 '2013-07-20': 28.0,
 '2013-07-21': 29.7,
 '2013-07-23': 28.9,
 '2013-07-24': 26.4,
 '2013-07-25': 30.0,
 '2013-07-27': 27.8,
 '2013-07-28': 26.7,
 '2013-08-01': 27.0,
 '2013-08-02': 26.8,
 '2013-08-04': 19.0,
 '2013-08-05': 21.4,
 '2013-08-06': 27.1,
 '2013-08-08': 26.3,
 '2013-08-09': 28.3,
 '2013-08-12': 27.9,
 '2013-08-13': 23.4,
 '2013-08-15': 23.5,
 '2013-08-18': 22.4,
 '2013-08-19': 26.8,
 '2013-08-20': 26.5,
 '2013-08-21': 22.0,
 '2013-08-23': 27.6,
 '2013-08-25': 25.6,
 '2013-08-26': 26.5,
 '2013-08-27': 24.0,
 '2013-08-28': 28.0,
 '2013-09-01': 28.0,
 '2013-09-02': 28.0,
 '2013-09-03': 27.0,
 '2013-09-04': 27.8,
 '2013-09-06': 23.4,
 '2013-09-07': 25.4,
 '2013-09-09': 26.3,
 '2013-09-10': 29.0,
 '2013-09-11': 24.6,
 '2013-09-13': 23.5,
 '2013-09-14': 29.0,
 '2013-09-15': 27.0,
 '2013-09-17': 24.0,
 '2013-09-18': 28.7,
 '2013-09-19': 26.3,
 '2013-09-20': 25.7,
 '2013-09-21': 27.0,
 '2013-09-22': 23.3,
 '2013-09-23': 22.8,
 '2013-09-24': 23.3,
 '2013-09-26': 21.8,
 '2013-09-28': 24.3,
 '2013-10-01': 23.5,
 '2013-10-03': 24.0,
 '2013-10-04': 23.5,
 '2013-10-06': 23.3,
 '2013-10-07': 22.5,
 '2013-10-08': 26.0,
 '2013-10-10': 25.8,
 '2013-10-11': 27.0,
 '2013-10-12': 27.0,
 '2013-10-13': 27.0,
 '2013-10-14': 27.0,
 '2013-10-15': 30.7,
 '2013-10-16': 20.3,
 '2013-10-17': 20.7,
 '2013-10-18': 20.8,
 '2013-10-19': 20.6,
 '2013-10-20': 28.0,
 '2013-10-21': 23.4,
 '2013-10-24': 25.3,
 '2013-10-25': 31.1,
 '2013-10-26': 26.3,
 '2013-10-27': 22.0,
 '2013-11-01': 24.4,
 '2013-11-02': 23.7,
 '2013-11-04': 24.6,
 '2013-11-05': 23.1,
 '2013-11-07': 18.2,
 '2013-11-08': 18.8,
 '2013-11-09': 23.8,
 '2013-11-10': 17.8,
 '2013-11-11': 18.7,
 '2013-11-13': 18.8,
 '2013-11-14': 22.6,
 '2013-11-17': 25.2,
 '2013-11-18': 24.8,
 '2013-11-20': 19.9,
 '2013-11-22': 20.7,
 '2013-11-24': 20.6,
 '2013-11-25': 21.5,
 '2013-11-26': 17.7,
 '2013-11-27': 17.9,
 '2013-11-28': 23.9,
 '2013-12-02': 18.0,
 '2013-12-03': 18.4,
 '2013-12-04': 18.8,
 '2013-12-06': 24.8,
 '2013-12-07': 19.3,
 '2013-12-08': 20.6,
 '2013-12-09': 20.7,
 '2013-12-12': 17.6,
 '2013-12-13': 22.7,
 '2013-12-15': 17.9,
 '2013-12-16': 19.4,
 '2013-12-18': 23.7,
 '2013-12-19': 22.7,
 '2013-12-20': 23.6,
 '2013-12-21': 23.8,
 '2013-12-22': 23.5,
 '2013-12-23': 23.5,
 '2013-12-25': 27.4,
 '2013-12-26': 21.9,
 '2013-12-28': 27.5,
 '2014-01-02': 30.6,
 '2014-01-03': 29.8,
 '2014-01-04': 29.5,
 '2014-01-05': 29.7,
 '2014-01-06': 29.5,
 '2014-01-07': 30.0,
 '2014-01-08': 29.2,
 '2014-01-10': 29.6,
 '2014-01-12': 30.0,
 '2014-01-13': 30.1,
 '2014-01-14': 27.8,
 '2014-01-15': 27.9,
 '2014-01-17': 29.3,
 '2014-01-21': 29.2,
 '2014-01-23': 30.0,
 '2014-01-28': 29.0,
 '2014-02-01': 29.1,
 '2014-02-02': 28.7,
 '2014-02-03': 28.7,
 '2014-02-04': 29.5,
 '2014-02-06': 29.0,
 '2014-02-07': 29.4,
 '2014-02-08': 30.1,
 '2014-02-09': 30.3,
 '2014-02-14': 30.5,
 '2014-02-17': 29.1,
 '2014-02-18': 30.1,
 '2014-02-19': 29.2,
 '2014-02-20': 25.1,
 '2014-02-23': 29.6,
 '2014-02-24': 27.4,
 '2014-02-25': 27.8,
 '2014-02-26': 30.6,
 '2014-03-01': 25.0,
 '2014-03-02': 25.0,
 '2014-03-03': 25.0,
 '2014-03-04': 25.1,
 '2014-03-05': 26.1,
 '2014-03-08': 21.4,
 '2014-03-09': 27.4,
 '2014-03-10': 27.1,
 '2014-03-12': 27.2,
 '2014-03-15': 27.3,
 '2014-03-16': 27.0,
 '2014-03-18': 27.2,
 '2014-03-20': 27.0,
 '2014-03-22': 22.6,
 '2014-03-24': 28.4,
 '2014-03-25': 28.0,
 '2014-03-26': 27.6,
 '2014-03-28': 27.9,
 '2014-04-02': 28.1,
 '2014-04-03': 27.1,
 '2014-04-04': 27.6,
 '2014-04-05': 27.3,
 '2014-04-07': 27.8,
 '2014-04-09': 28.0,
 '2014-04-11': 28.1,
 '2014-04-12': 28.6,
 '2014-04-13': 26.9,
 '2014-04-14': 23.0,
 '2014-04-15': 23.0,
 '2014-04-16': 23.0,
 '2014-04-17': 25.1,
 '2014-04-18': 24.6,
 '2014-04-19': 25.7,
 '2014-04-20': 24.8,
 '2014-04-21': 27.3,
 '2014-04-22': 27.5,
 '2014-04-23': 25.2,
 '2014-04-25': 29.9,
 '2014-04-28': 29.8,
 '2014-05-02': 27.8,
 '2014-05-03': 26.7,
 '2014-05-04': 25.8,
 '2014-05-05': 26.4,
 '2014-05-06': 29.8,
 '2014-05-08': 28.6,
 '2014-05-11': 26.9,
 '2014-05-12': 26.0,
 '2014-05-13': 23.6,
 '2014-05-14': 30.3,
 '2014-05-15': 30.7,
 '2014-05-16': 28.2,
 '2014-05-17': 24.8,
 '2014-05-18': 29.2,
 '2014-05-20': 26.6,
 '2014-05-21': 30.4,
 '2014-05-24': 25.1,
 '2014-05-25': 28.9,
 '2014-05-26': 28.8,
 '2014-06-01': 29.3,
 '2014-06-02': 29.5,
 '2014-06-03': 28.4,
 '2014-06-05': 26.9,
 '2014-06-06': 25.8,
 '2014-06-07': 26.6,
 '2014-06-08': 25.3,
 '2014-06-09': 28.2,
 '2014-06-10': 28.5,
 '2014-06-11': 27.6,
 '2014-06-12': 29.0,
 '2014-06-13': 27.5,
 '2014-06-15': 27.8,
 '2014-06-16': 30.2,
 '2014-06-19': 25.3,
 '2014-06-20': 25.3,
 '2014-06-22': 25.8,
 '2014-06-23': 27.2,
 '2014-06-27': 28.1,
 '2014-06-28': 28.3,
 '2014-07-01': 28.1,
 '2014-07-04': 27.7,
 '2014-07-06': 28.0,
 '2014-07-07': 28.2,
 '2014-07-08': 28.0,
 '2014-07-09': 28.1,
 '2014-07-13': 28.1,
 '2014-07-14': 28.1,
 '2014-07-15': 27.3,
 '2014-07-16': 28.3,
 '2014-07-17': 29.1,
 '2014-07-18': 28.7,
 '2014-07-21': 28.5,
 '2014-07-23': 26.6,
 '2014-07-24': 31.0,
 '2014-07-25': 28.8,
 '2014-07-26': 25.3,
 '2014-07-27': 25.9,
 '2014-08-02': 26.5,
 '2014-08-04': 18.9,
 '2014-08-05': 20.5,
 '2014-08-08': 27.1,
 '2014-08-09': 26.3,
 '2014-08-10': 29.1,
 '2014-08-11': 28.4,
 '2014-08-12': 24.7,
 '2014-08-13': 24.4,
 '2014-08-15': 22.7,
 '2014-08-18': 24.8,
 '2014-08-19': 24.0,
 '2014-08-21': 22.8,
 '2014-08-22': 26.8,
 '2014-08-23': 25.3,
 '2014-08-25': 27.1,
 '2014-08-27': 29.0,
 '2014-08-28': 32.0,
 '2014-09-01': 29.3,
 '2014-09-02': 22.8,
 '2014-09-03': 24.5,
 '2014-09-04': 25.5,
 '2014-09-05': 29.0,
 '2014-09-06': 23.8,
 '2014-09-07': 22.8,
 '2014-09-09': 29.0,
 '2014-09-10': 29.0,
 '2014-09-11': 23.0,
 '2014-09-12': 29.0,
 '2014-09-13': 25.7,
 '2014-09-14': 25.7,
 '2014-09-15': 27.0,
 '2014-09-16': 22.7,
 '2014-09-17': 19.0,
 '2014-09-18': 23.0,
 '2014-09-20': 24.0,
 '2014-09-22': 24.7,
 '2014-09-23': 25.0,
 '2014-09-26': 22.0,
 '2014-09-27': 24.3,
 '2014-09-28': 23.3,
 '2014-10-01': 19.5,
 '2014-10-02': 21.5,
 '2014-10-03': 20.0,
 '2014-10-04': 27.0,
 '2014-10-05': 27.0,
 '2014-10-06': 32.6,
 '2014-10-08': 23.6,
 '2014-10-09': 23.9,
 '2014-10-11': 24.5,
 '2014-10-12': 27.0,
 '2014-10-13': 18.1,
 '2014-10-15': 25.1,
 '2014-10-16': 22.3,
 '2014-10-21': 23.7,
 '2014-10-22': 23.9,
 '2014-10-23': 25.5,
 '2014-10-25': 25.1,
 '2014-11-01': 25.2,
 '2014-11-02': 23.2,
 '2014-11-03': 18.3,
 '2014-11-05': 19.3,
 '2014-11-06': 24.0,
 '2014-11-07': 21.2,
 '2014-11-08': 26.3,
 '2014-11-09': 25.5,
 '2014-11-10': 20.0,
 '2014-11-11': 20.3,
 '2014-11-14': 19.4,
 '2014-11-15': 21.0,
 '2014-11-16': 19.2,
 '2014-11-17': 18.3,
 '2014-11-18': 19.6,
 '2014-11-19': 23.7,
 '2014-11-21': 18.2,
 '2014-11-23': 18.8,
 '2014-11-24': 18.9,
 '2014-11-25': 25.1,
 '2014-11-27': 18.8,
 '2014-12-01': 20.2,
 '2014-12-02': 20.0,
 '2014-12-03': 18.8,
 '2014-12-04': 18.2,
 '2014-12-06': 22.1,
 '2014-12-07': 17.6,
 '2014-12-12': 18.7,
 '2014-12-13': 23.1,
 '2014-12-14': 22.6,
 '2014-12-16': 20.0,
 '2014-12-17': 19.9,
 '2014-12-18': 24.5,
 '2014-12-21': 24.4,
 '2014-12-22': 23.6,
 '2014-12-24': 23.5,
 '2014-12-25': 27.3,
 '2014-12-26': 29.1,
 '2014-12-27': 26.6}

In [27]:
data.describe()

,STATION CODE,Temp,D.O. (mg/l),PH,CONDUCTIVITY (Âµmhos/cm),B.O.D. (mg/l),NITRATENAN N+ NITRITENANN (mg/l),FECAL COLIFORM (MPN/100ml),TOTAL COLIFORM (MPN/100ml)Mean,year
count,736.000000,738.000000,738.000000,738.000000,738.000000,738.000000,738.000000,738.000000,738.000000,738.000000
mean,2252.947011,26.228320,6.583198,7.290379,909.699187,3.694537,1.279350,2128.460705,3947.182927,2012.943089
std,813.619235,3.323943,1.063475,0.440368,2574.757652,6.421942,1.768243,6397.810887,11161.052236,0.816726
min,17.000000,17.000000,2.400000,5.600000,30.000000,0.100000,0.000000,2.000000,0.000000,2012.000000
25%,1567.000000,24.075000,6.100000,7.000000,74.250000,1.200000,0.250000,30.000000,67.000000,2012.000000
50%,2297.000000,27.000000,6.700000,7.300000,144.000000,1.800000,0.545000,233.000000,420.000000,2013.000000
75%,2877.250000,28.875000,7.200000,7.600000,352.750000,3.100000,1.580000,616.750000,1556.750000,2014.000000
max,3473.000000,33.000000,9.900000,8.400000,18569.000000,88.000000,11.810000,53083.000000,87167.000000,2014.000000

In [28]:
dict_temp = dict(zip(dates, data["Temp"].values))
dict_do = dict(zip(dates, data["D.O. (mg/l)"].values))
dict_ph = dict(zip(dates, data["PH"].values))
dict_conductivity = dict(zip(dates, data["CONDUCTIVITY (Âµmhos/cm)"].values))
dict_bod = dict(zip(dates, data["B.O.D. (mg/l)"].values))
dict_nitra = dict(zip(dates, data["NITRATENAN N+ NITRITENANN (mg/l)"].values))
dict_fecal = dict(zip(dates, data["FECAL COLIFORM (MPN/100ml)"].values))

In [29]:
dict_temp

{'2012-01-01': 31.0,
 '2012-01-04': 28.0,
 '2012-01-05': 27.0,
 '2012-01-06': 29.0,
 '2012-01-07': 31.0,
 '2012-01-10': 30.0,
 '2012-01-13': 30.0,
 '2012-01-15': 29.0,
 '2012-01-16': 29.0,
 '2012-01-17': 29.0,
 '2012-01-18': 28.0,
 '2012-01-20': 30.0,
 '2012-01-22': 30.0,
 '2012-01-23': 27.0,
 '2012-01-26': 28.0,
 '2012-01-27': 29.0,
 '2012-01-28': 28.0,
 '2012-02-02': 29.0,
 '2012-02-04': 29.0,
 '2012-02-05': 30.0,
 '2012-02-06': 28.0,
 '2012-02-10': 28.0,
 '2012-02-11': 29.0,
 '2012-02-12': 28.0,
 '2012-02-13': 30.0,
 '2012-02-15': 30.0,
 '2012-02-16': 31.0,
 '2012-02-18': 29.0,
 '2012-02-19': 30.0,
 '2012-02-20': 29.0,
 '2012-02-21': 29.0,
 '2012-02-22': 29.0,
 '2012-02-24': 29.0,
 '2012-02-25': 30.0,
 '2012-02-27': 27.0,
 '2012-03-01': 27.0,
 '2012-03-02': 27.0,
 '2012-03-03': 23.0,
 '2012-03-04': 29.0,
 '2012-03-05': 29.0,
 '2012-03-06': 29.0,
 '2012-03-07': 28.0,
 '2012-03-08': 29.0,
 '2012-03-09': 29.0,
 '2012-03-10': 29.0,
 '2012-03-11': 29.0,
 '2012-03-12': 30.0,
 '2012-03-14': 30.0,
 '2012-03-16': 29.0,
 '2012-03-17': 25.0,
 '2012-03-18': 30.0,
 '2012-03-19': 30.0,
 '2012-03-20': 31.0,
 '2012-03-22': 30.0,
 '2012-03-23': 30.0,
 '2012-03-24': 28.0,
 '2012-03-26': 28.0,
 '2012-03-27': 28.0,
 '2012-03-28': 27.0,
 '2012-04-01': 27.0,
 '2012-04-02': 26.0,
 '2012-04-04': 27.0,
 '2012-04-05': 28.0,
 '2012-04-06': 23.0,
 '2012-04-07': 22.0,
 '2012-04-09': 23.0,
 '2012-04-10': 26.0,
 '2012-04-11': 26.0,
 '2012-04-12': 26.0,
 '2012-04-13': 26.0,
 '2012-04-14': 26.0,
 '2012-04-15': 26.0,
 '2012-04-16': 29.0,
 '2012-04-17': 28.0,
 '2012-04-18': 28.0,
 '2012-04-19': 29.0,
 '2012-04-20': 26.0,
 '2012-04-21': 26.0,
 '2012-04-22': 28.0,
 '2012-04-23': 29.0,
 '2012-04-24': 26.0,
 '2012-04-25': 26.0,
 '2012-04-26': 25.0,
 '2012-04-27': 29.0,
 '2012-04-28': 29.0,
 '2012-05-01': 25.0,
 '2012-05-02': 27.0,
 '2012-05-03': 27.0,
 '2012-05-04': 29.0,
 '2012-05-05': 29.0,
 '2012-05-06': 29.0,
 '2012-05-07': 27.0,
 '2012-05-08': 30.0,
 '2012-05-10': 27.0,
 '2012-05-12': 27.0,
 '2012-05-13': 25.0,
 '2012-05-14': 25.0,
 '2012-05-15': 26.0,
 '2012-05-16': 29.0,
 '2012-05-17': 27.0,
 '2012-05-18': 27.0,
 '2012-05-19': 27.0,
 '2012-05-22': 28.0,
 '2012-05-23': 26.0,
 '2012-05-24': 29.0,
 '2012-05-25': 27.0,
 '2012-05-27': 28.0,
 '2012-05-28': 29.0,
 '2012-06-01': 28.0,
 '2012-06-02': 29.0,
 '2012-06-03': 26.0,
 '2012-06-04': 28.0,
 '2012-06-05': 28.0,
 '2012-06-06': 28.0,
 '2012-06-07': 28.0,
 '2012-06-08': 27.0,
 '2012-06-09': 28.0,
 '2012-06-10': 28.0,
 '2012-06-11': 28.0,
 '2012-06-12': 28.0,
 '2012-06-14': 28.0,
 '2012-06-15': 28.0,
 '2012-06-16': 26.0,
 '2012-06-17': 28.0,
 '2012-06-18': 29.0,
 '2012-06-19': 28.0,
 '2012-06-20': 26.0,
 '2012-06-21': 29.0,
 '2012-06-22': 29.0,
 '2012-06-24': 27.0,
 '2012-06-25': 29.0,
 '2012-06-27': 27.0,
 '2012-06-28': 27.0,
 '2012-07-01': 20.0,
 '2012-07-03': 24.0,
 '2012-07-04': 28.0,
 '2012-07-05': 27.0,
 '2012-07-07': 32.0,
 '2012-07-08': 30.0,
 '2012-07-09': 22.0,
 '2012-07-10': 22.0,
 '2012-07-11': 24.0,
 '2012-07-12': 27.0,
 '2012-07-14': 26.0,
 '2012-07-15': 25.0,
 '2012-07-16': 28.0,
 '2012-07-17': 26.0,
 '2012-07-18': 28.0,
 '2012-07-19': 31.0,
 '2012-07-20': 25.0,
 '2012-07-21': 25.0,
 '2012-07-23': 25.0,
 '2012-07-24': 27.0,
 '2012-07-25': 23.0,
 '2012-07-26': 25.0,
 '2012-07-27': 26.0,
 '2012-07-28': 29.0,
 '2012-08-01': 24.0,
 '2012-08-03': 24.0,
 '2012-08-04': 29.0,
 '2012-08-05': 29.0,
 '2012-08-06': 24.0,
 '2012-08-07': 29.0,
 '2012-08-08': 26.0,
 '2012-08-10': 27.0,
 '2012-08-11': 27.0,
 '2012-08-12': 21.0,
 '2012-08-13': 24.0,
 '2012-08-14': 21.0,
 '2012-08-15': 24.0,
 '2012-08-16': 21.0,
 '2012-08-17': 18.0,
 '2012-08-18': 22.0,
 '2012-08-19': 22.0,
 '2012-08-20': 24.0,
 '2012-08-21': 22.0,
 '2012-08-22': 22.0,
 '2012-08-23': 27.0,
 '2012-08-24': 27.0,
 '2012-08-25': 27.0,
 '2012-08-26': 33.0,
 '2012-08-27': 20.0,
 '2012-08-28': 20.0,
 '2012-09-01': 20.0,
 '2012-09-02': 18.0,
 '2012-09-03': 24.0,
 '2012-09-04': 19.0,
 '2012-09-05': 23.0,
 '2012-09-06': 24.0,
 '2012-09-07': 23.0,
 '2012-09-08': 28.0,
 '2012-09-09': 29.0,
 '2012-09-11': 30.0,
 '2012-09-13': 30.0,
 '2012-09-15': 28.0,
 '2012-09-16': 29.0,
 '2012-09-17': 30.0,
 '2012-09-18': 29.0,
 '2012-09-19': 28.0,
 '2012-09-20': 28.0,
 '2012-09-21': 30.0,
 '2012-09-24': 28.0,
 '2012-09-26': 29.0,
 '2012-09-27': 28.0,
 '2012-09-28': 29.0,
 '2012-10-01': 32.0,
 '2012-10-04': 32.0,
 '2012-10-05': 30.0,
 '2012-10-06': 29.0,
 '2012-10-08': 31.0,
 '2012-10-10': 29.0,
 '2012-10-11': 30.0,
 '2012-10-12': 29.0,
 '2012-10-15': 30.0,
 '2012-10-16': 29.0,
 '2012-10-17': 29.0,
 '2012-10-18': 30.0,
 '2012-10-19': 29.0,
 '2012-10-22': 29.0,
 '2012-10-24': 28.0,
 '2012-10-25': 29.0,
 '2012-10-28': 29.0,
 '2012-11-01': 30.0,
 '2012-11-02': 28.0,
 '2012-11-03': 28.0,
 '2012-11-04': 29.0,
 '2012-11-05': 30.0,
 '2012-11-06': 30.0,
 '2012-11-07': 25.0,
 '2012-11-08': 25.0,
 '2012-11-09': 25.0,
 '2012-11-10': 24.0,
 '2012-11-13': 17.0,
 '2012-11-14': 23.0,
 '2012-11-16': 25.0,
 '2012-11-19': 25.0,
 '2012-11-20': 25.0,
 '2012-11-21': 20.0,
 '2012-11-22': 22.0,
 '2012-11-23': 20.0,
 '2012-11-24': 21.0,
 '2012-11-25': 17.0,
 '2012-11-26': 17.0,
 '2012-11-27': 24.0,
 '2012-11-28': 18.0,
 '2012-12-01': 18.0,
 '2012-12-02': 18.0,
 '2012-12-03': 25.0,
 '2012-12-04': 19.0,
 '2012-12-05': 21.0,
 '2012-12-06': 21.0,
 '2012-12-07': 18.0,
 '2012-12-08': 19.0,
 '2012-12-09': 18.0,
 '2012-12-10': 24.0,
 '2012-12-11': 17.0,
 '2012-12-12': 19.0,
 '2012-12-15': 24.0,
 '2012-12-17': 22.0,
 '2012-12-18': 20.0,
 '2012-12-19': 20.0,
 '2012-12-20': 24.0,
 '2012-12-21': 24.0,
 '2012-12-22': 24.0,
 '2012-12-23': 24.0,
 '2012-12-24': 28.0,
 '2012-12-25': 28.0,
 '2012-12-27': 27.0,
 '2013-01-01': 27.1,
 '2013-01-02': 27.3,
 '2013-01-03': 24.5,
 '2013-01-05': 27.5,
 '2013-01-07': 28.4,
 '2013-01-08': 27.0,
 '2013-01-09': 27.6,
 '2013-01-11': 27.0,
 '2013-01-12': 27.0,
 '2013-01-13': 27.0,
 '2013-01-15': 29.0,
 '2013-01-16': 27.0,
 '2013-01-17': 30.0,
 '2013-01-18': 30.4,
 '2013-01-20': 30.8,
 '2013-01-21': 30.3,
 '2013-01-22': 30.1,
 '2013-01-25': 29.9,
 '2013-01-26': 29.1,
 '2013-01-27': 29.9,
 '2013-02-01': 29.8,
 '2013-02-02': 27.9,
 '2013-02-06': 28.2,
 '2013-02-07': 29.6,
 '2013-02-08': 28.8,
 '2013-02-10': 29.5,
 '2013-02-12': 29.8,
 '2013-02-13': 29.7,
 '2013-02-14': 28.7,
 '2013-02-15': 27.9,
 '2013-02-17': 29.3,
 '2013-02-18': 28.6,
 '2013-02-20': 29.8,
 '2013-02-21': 28.6,
 '2013-02-22': 30.6,
 '2013-02-23': 30.3,
 '2013-02-24': 30.4,
 '2013-02-25': 29.6,
 '2013-02-26': 29.6,
 '2013-02-27': 29.5,
 '2013-02-28': 26.7,
 '2013-03-01': 29.3,
 '2013-03-02': 28.0,
 '2013-03-04': 28.2,
 '2013-03-05': 26.5,
 '2013-03-06': 20.7,
 '2013-03-07': 27.2,
 '2013-03-09': 27.5,
 '2013-03-10': 26.0,
 '2013-03-11': 26.5,
 '2013-03-12': 27.0,
 '2013-03-13': 27.3,
 '2013-03-14': 28.7,
 '2013-03-16': 28.4,
 '2013-03-17': 28.7,
 '2013-03-18': 28.7,
 '2013-03-20': 28.7,
 '2013-03-21': 28.7,
 '2013-03-22': 28.7,
 '2013-03-23': 29.3,
 '2013-03-24': 28.3,
 '2013-03-25': 28.7,
 '2013-03-27': 29.2,
 '2013-03-28': 28.7,
 '2013-04-01': 27.2,
 '2013-04-03': 27.2,
 '2013-04-04': 27.2,
 '2013-04-05': 28.0,
 '2013-04-08': 26.2,
 '2013-04-09': 26.2,
 '2013-04-10': 28.2,
 '2013-04-11': 24.5,
 '2013-04-12': 24.5,
 '2013-04-13': 24.5,
 '2013-04-15': 24.0,
 '2013-04-16': 24.9,
 '2013-04-17': 24.3,
 '2013-04-19': 24.8,
 '2013-04-20': 26.4,
 '2013-04-21': 27.0,
 '2013-04-24': 26.6,
 '2013-04-25': 28.6,
 '2013-04-26': 28.8,
 '2013-04-27': 28.0,
 '2013-05-01': 27.4,
 '2013-05-06': 27.5,
 '2013-05-07': 26.8,
 '2013-05-08': 30.0,
 '2013-05-09': 28.8,
 '2013-05-10': 27.4,
 '2013-05-12': 24.8,
 '2013-05-13': 23.6,
 '2013-05-16': 29.8,
 '2013-05-17': 30.2,
 '2013-05-19': 28.2,
 '2013-05-21': 27.7,
 '2013-05-22': 23.9,
 '2013-05-23': 27.8,
 '2013-05-24': 26.4,
 '2013-05-25': 29.6,
 '2013-05-27': 27.0,
 '2013-06-01': 26.3,
 '2013-06-03': 30.0,
 '2013-06-04': 28.0,
 '2013-06-05': 30.1,
 '2013-06-06': 27.9,
 '2013-06-07': 27.0,
 '2013-06-08': 26.0,
 '2013-06-09': 27.7,
 '2013-06-11': 27.1,
 '2013-06-13': 26.5,
 '2013-06-14': 28.5,
 '2013-06-15': 28.7,
 '2013-06-17': 25.7,
 '2013-06-18': 29.3,
 '2013-06-19': 27.0,
 '2013-06-20': 27.1,
 '2013-06-21': 30.3,
 '2013-06-22': 30.4,
 '2013-06-23': 26.2,
 '2013-06-24': 26.2,
 '2013-06-27': 25.1,
 '2013-07-01': 27.4,
 '2013-07-02': 28.1,
 '2013-07-04': 28.3,
 '2013-07-05': 28.2,
 '2013-07-07': 27.2,
 '2013-07-09': 27.4,
 '2013-07-10': 28.2,
 '2013-07-11': 27.9,
 '2013-07-13': 27.3,
 '2013-07-16': 28.2,
 '2013-07-17': 28.2,
 '2013-07-19': 26.7,
 '2013-07-20': 28.0,
 '2013-07-21': 29.7,
 '2013-07-23': 28.9,
 '2013-07-24': 26.4,
 '2013-07-25': 30.0,
 '2013-07-27': 27.8,
 '2013-07-28': 26.7,
 '2013-08-01': 27.0,
 '2013-08-02': 26.8,
 '2013-08-04': 19.0,
 '2013-08-05': 21.4,
 '2013-08-06': 27.1,
 '2013-08-08': 26.3,
 '2013-08-09': 28.3,
 '2013-08-12': 27.9,
 '2013-08-13': 23.4,
 '2013-08-15': 23.5,
 '2013-08-18': 22.4,
 '2013-08-19': 26.8,
 '2013-08-20': 26.5,
 '2013-08-21': 22.0,
 '2013-08-23': 27.6,
 '2013-08-25': 25.6,
 '2013-08-26': 26.5,
 '2013-08-27': 24.0,
 '2013-08-28': 28.0,
 '2013-09-01': 28.0,
 '2013-09-02': 28.0,
 '2013-09-03': 27.0,
 '2013-09-04': 27.8,
 '2013-09-06': 23.4,
 '2013-09-07': 25.4,
 '2013-09-09': 26.3,
 '2013-09-10': 29.0,
 '2013-09-11': 24.6,
 '2013-09-13': 23.5,
 '2013-09-14': 29.0,
 '2013-09-15': 27.0,
 '2013-09-17': 24.0,
 '2013-09-18': 28.7,
 '2013-09-19': 26.3,
 '2013-09-20': 25.7,
 '2013-09-21': 27.0,
 '2013-09-22': 23.3,
 '2013-09-23': 22.8,
 '2013-09-24': 23.3,
 '2013-09-26': 21.8,
 '2013-09-28': 24.3,
 '2013-10-01': 23.5,
 '2013-10-03': 24.0,
 '2013-10-04': 23.5,
 '2013-10-06': 23.3,
 '2013-10-07': 22.5,
 '2013-10-08': 26.0,
 '2013-10-10': 25.8,
 '2013-10-11': 27.0,
 '2013-10-12': 27.0,
 '2013-10-13': 27.0,
 '2013-10-14': 27.0,
 '2013-10-15': 30.7,
 '2013-10-16': 20.3,
 '2013-10-17': 20.7,
 '2013-10-18': 20.8,
 '2013-10-19': 20.6,
 '2013-10-20': 28.0,
 '2013-10-21': 23.4,
 '2013-10-24': 25.3,
 '2013-10-25': 31.1,
 '2013-10-26': 26.3,
 '2013-10-27': 22.0,
 '2013-11-01': 24.4,
 '2013-11-02': 23.7,
 '2013-11-04': 24.6,
 '2013-11-05': 23.1,
 '2013-11-07': 18.2,
 '2013-11-08': 18.8,
 '2013-11-09': 23.8,
 '2013-11-10': 17.8,
 '2013-11-11': 18.7,
 '2013-11-13': 18.8,
 '2013-11-14': 22.6,
 '2013-11-17': 25.2,
 '2013-11-18': 24.8,
 '2013-11-20': 19.9,
 '2013-11-22': 20.7,
 '2013-11-24': 20.6,
 '2013-11-25': 21.5,
 '2013-11-26': 17.7,
 '2013-11-27': 17.9,
 '2013-11-28': 23.9,
 '2013-12-02': 18.0,
 '2013-12-03': 18.4,
 '2013-12-04': 18.8,
 '2013-12-06': 24.8,
 '2013-12-07': 19.3,
 '2013-12-08': 20.6,
 '2013-12-09': 20.7,
 '2013-12-12': 17.6,
 '2013-12-13': 22.7,
 '2013-12-15': 17.9,
 '2013-12-16': 19.4,
 '2013-12-18': 23.7,
 '2013-12-19': 22.7,
 '2013-12-20': 23.6,
 '2013-12-21': 23.8,
 '2013-12-22': 23.5,
 '2013-12-23': 23.5,
 '2013-12-25': 27.4,
 '2013-12-26': 21.9,
 '2013-12-28': 27.5,
 '2014-01-02': 30.6,
 '2014-01-03': 29.8,
 '2014-01-04': 29.5,
 '2014-01-05': 29.7,
 '2014-01-06': 29.5,
 '2014-01-07': 30.0,
 '2014-01-08': 29.2,
 '2014-01-10': 29.6,
 '2014-01-12': 30.0,
 '2014-01-13': 30.1,
 '2014-01-14': 27.8,
 '2014-01-15': 27.9,
 '2014-01-17': 29.3,
 '2014-01-21': 29.2,
 '2014-01-23': 30.0,
 '2014-01-28': 29.0,
 '2014-02-01': 29.1,
 '2014-02-02': 28.7,
 '2014-02-03': 28.7,
 '2014-02-04': 29.5,
 '2014-02-06': 29.0,
 '2014-02-07': 29.4,
 '2014-02-08': 30.1,
 '2014-02-09': 30.3,
 '2014-02-14': 30.5,
 '2014-02-17': 29.1,
 '2014-02-18': 30.1,
 '2014-02-19': 29.2,
 '2014-02-20': 25.1,
 '2014-02-23': 29.6,
 '2014-02-24': 27.4,
 '2014-02-25': 27.8,
 '2014-02-26': 30.6,
 '2014-03-01': 25.0,
 '2014-03-02': 25.0,
 '2014-03-03': 25.0,
 '2014-03-04': 25.1,
 '2014-03-05': 26.1,
 '2014-03-08': 21.4,
 '2014-03-09': 27.4,
 '2014-03-10': 27.1,
 '2014-03-12': 27.2,
 '2014-03-15': 27.3,
 '2014-03-16': 27.0,
 '2014-03-18': 27.2,
 '2014-03-20': 27.0,
 '2014-03-22': 22.6,
 '2014-03-24': 28.4,
 '2014-03-25': 28.0,
 '2014-03-26': 27.6,
 '2014-03-28': 27.9,
 '2014-04-02': 28.1,
 '2014-04-03': 27.1,
 '2014-04-04': 27.6,
 '2014-04-05': 27.3,
 '2014-04-07': 27.8,
 '2014-04-09': 28.0,
 '2014-04-11': 28.1,
 '2014-04-12': 28.6,
 '2014-04-13': 26.9,
 '2014-04-14': 23.0,
 '2014-04-15': 23.0,
 '2014-04-16': 23.0,
 '2014-04-17': 25.1,
 '2014-04-18': 24.6,
 '2014-04-19': 25.7,
 '2014-04-20': 24.8,
 '2014-04-21': 27.3,
 '2014-04-22': 27.5,
 '2014-04-23': 25.2,
 '2014-04-25': 29.9,
 '2014-04-28': 29.8,
 '2014-05-02': 27.8,
 '2014-05-03': 26.7,
 '2014-05-04': 25.8,
 '2014-05-05': 26.4,
 '2014-05-06': 29.8,
 '2014-05-08': 28.6,
 '2014-05-11': 26.9,
 '2014-05-12': 26.0,
 '2014-05-13': 23.6,
 '2014-05-14': 30.3,
 '2014-05-15': 30.7,
 '2014-05-16': 28.2,
 '2014-05-17': 24.8,
 '2014-05-18': 29.2,
 '2014-05-20': 26.6,
 '2014-05-21': 30.4,
 '2014-05-24': 25.1,
 '2014-05-25': 28.9,
 '2014-05-26': 28.8,
 '2014-06-01': 29.3,
 '2014-06-02': 29.5,
 '2014-06-03': 28.4,
 '2014-06-05': 26.9,
 '2014-06-06': 25.8,
 '2014-06-07': 26.6,
 '2014-06-08': 25.3,
 '2014-06-09': 28.2,
 '2014-06-10': 28.5,
 '2014-06-11': 27.6,
 '2014-06-12': 29.0,
 '2014-06-13': 27.5,
 '2014-06-15': 27.8,
 '2014-06-16': 30.2,
 '2014-06-19': 25.3,
 '2014-06-20': 25.3,
 '2014-06-22': 25.8,
 '2014-06-23': 27.2,
 '2014-06-27': 28.1,
 '2014-06-28': 28.3,
 '2014-07-01': 28.1,
 '2014-07-04': 27.7,
 '2014-07-06': 28.0,
 '2014-07-07': 28.2,
 '2014-07-08': 28.0,
 '2014-07-09': 28.1,
 '2014-07-13': 28.1,
 '2014-07-14': 28.1,
 '2014-07-15': 27.3,
 '2014-07-16': 28.3,
 '2014-07-17': 29.1,
 '2014-07-18': 28.7,
 '2014-07-21': 28.5,
 '2014-07-23': 26.6,
 '2014-07-24': 31.0,
 '2014-07-25': 28.8,
 '2014-07-26': 25.3,
 '2014-07-27': 25.9,
 '2014-08-02': 26.5,
 '2014-08-04': 18.9,
 '2014-08-05': 20.5,
 '2014-08-08': 27.1,
 '2014-08-09': 26.3,
 '2014-08-10': 29.1,
 '2014-08-11': 28.4,
 '2014-08-12': 24.7,
 '2014-08-13': 24.4,
 '2014-08-15': 22.7,
 '2014-08-18': 24.8,
 '2014-08-19': 24.0,
 '2014-08-21': 22.8,
 '2014-08-22': 26.8,
 '2014-08-23': 25.3,
 '2014-08-25': 27.1,
 '2014-08-27': 29.0,
 '2014-08-28': 32.0,
 '2014-09-01': 29.3,
 '2014-09-02': 22.8,
 '2014-09-03': 24.5,
 '2014-09-04': 25.5,
 '2014-09-05': 29.0,
 '2014-09-06': 23.8,
 '2014-09-07': 22.8,
 '2014-09-09': 29.0,
 '2014-09-10': 29.0,
 '2014-09-11': 23.0,
 '2014-09-12': 29.0,
 '2014-09-13': 25.7,
 '2014-09-14': 25.7,
 '2014-09-15': 27.0,
 '2014-09-16': 22.7,
 '2014-09-17': 19.0,
 '2014-09-18': 23.0,
 '2014-09-20': 24.0,
 '2014-09-22': 24.7,
 '2014-09-23': 25.0,
 '2014-09-26': 22.0,
 '2014-09-27': 24.3,
 '2014-09-28': 23.3,
 '2014-10-01': 19.5,
 '2014-10-02': 21.5,
 '2014-10-03': 20.0,
 '2014-10-04': 27.0,
 '2014-10-05': 27.0,
 '2014-10-06': 32.6,
 '2014-10-08': 23.6,
 '2014-10-09': 23.9,
 '2014-10-11': 24.5,
 '2014-10-12': 27.0,
 '2014-10-13': 18.1,
 '2014-10-15': 25.1,
 '2014-10-16': 22.3,
 '2014-10-21': 23.7,
 '2014-10-22': 23.9,
 '2014-10-23': 25.5,
 '2014-10-25': 25.1,
 '2014-11-01': 25.2,
 '2014-11-02': 23.2,
 '2014-11-03': 18.3,
 '2014-11-05': 19.3,
 '2014-11-06': 24.0,
 '2014-11-07': 21.2,
 '2014-11-08': 26.3,
 '2014-11-09': 25.5,
 '2014-11-10': 20.0,
 '2014-11-11': 20.3,
 '2014-11-14': 19.4,
 '2014-11-15': 21.0,
 '2014-11-16': 19.2,
 '2014-11-17': 18.3,
 '2014-11-18': 19.6,
 '2014-11-19': 23.7,
 '2014-11-21': 18.2,
 '2014-11-23': 18.8,
 '2014-11-24': 18.9,
 '2014-11-25': 25.1,
 '2014-11-27': 18.8,
 '2014-12-01': 20.2,
 '2014-12-02': 20.0,
 '2014-12-03': 18.8,
 '2014-12-04': 18.2,
 '2014-12-06': 22.1,
 '2014-12-07': 17.6,
 '2014-12-12': 18.7,
 '2014-12-13': 23.1,
 '2014-12-14': 22.6,
 '2014-12-16': 20.0,
 '2014-12-17': 19.9,
 '2014-12-18': 24.5,
 '2014-12-21': 24.4,
 '2014-12-22': 23.6,
 '2014-12-24': 23.5,
 '2014-12-25': 27.3,
 '2014-12-26': 29.1,
 '2014-12-27': 26.6}

In [30]:
from collections import defaultdict
from datetime import datetime
import calendar

def calculate_monthly_mean(data):
    # Create a defaultdict to store measurements for each month for each year
    yearly_monthly_data = defaultdict(lambda: defaultdict(list))

    # Iterate through the data and add measurements to the corresponding month and year
    for date_str, value in data.items():
        date = datetime.strptime(date_str, "%Y-%m-%d")
        year = date.year
        month = date.month
        yearly_monthly_data[year][month].append(value)

    mean_data = {}
    for year, monthly_data in yearly_monthly_data.items():
        mean_data[year] = {}
        for month, values in monthly_data.items():
            month_name = calendar.month_name[month]
            mean_data[year][month_name] = sum(values) / len(values)

    return mean_data

In [31]:
calculate_monthly_mean(dict_temp).values()

dict_values([{'January': 29.0, 'February': 29.11111111111111, 'March': 28.5, 'April': 26.53846153846154, 'May': 27.391304347826086, 'June': 27.8, 'July': 26.041666666666668, 'August': 24.384615384615383, 'September': 26.545454545454547, 'October': 29.647058823529413, 'November': 23.82608695652174, 'December': 21.82608695652174}, {'January': 28.345, 'February': 29.18571428571429, 'March': 27.782608695652176, 'April': 26.354999999999997, 'May': 27.46470588235294, 'June': 27.671428571428578, 'July': 27.92631578947368, 'August': 25.268421052631584, 'September': 25.736363636363635, 'October': 24.809090909090912, 'November': 21.334999999999997, 'December': 21.79}, {'January': 29.45, 'February': 29.070588235294125, 'March': 26.238888888888887, 'April': 26.59047619047619, 'May': 27.610526315789468, 'June': 27.53, 'July': 27.98888888888889, 'August': 25.57777777777778, 'September': 24.960869565217386, 'October': 24.13529411764706, 'November': 21.157142857142862, 'December': 22.233333333333334}])

In [56]:
from scipy.stats import zscore
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn import neural_network

In [120]:
data = pd.read_csv("../backend/dataset/indian_water_physicochemical_parameters.csv", encoding = 'unicode_escape')
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data['date'] = pd.to_datetime(data['date'])
data

,STATION CODE,LOCATIONS,STATE,Temp,D.O. (mg/l),PH,CONDUCTIVITY (Âµmhos/cm),B.O.D. (mg/l),NITRATENAN N+ NITRITENANN (mg/l),FECAL COLIFORM (MPN/100ml),TOTAL COLIFORM (MPN/100ml)Mean,year,date
0,1393.0,DAMANGANGA AT D/S OF MADHUBAN,DAMAN & DIU,31.0,7.1,7.8,151.0,8.0,0.08,233.0,465.0,2012,2012-01-01
1,1150.0,DAMANGANGA AT KACHIGAON U\S AT GIDC WIER,GUJARAT,28.0,7.2,7.4,319.0,0.7,0.18,5.0,10.0,2012,2012-01-04
2,1865.0,RIVER DHADAR AT KOTHADA,GUJARAT,27.0,6.2,8.4,894.0,9.0,0.38,140.0,350.0,2012,2012-01-05
3,1149.0,KOLAK AT PATALIA BDG,GUJARAT,29.0,2.4,7.6,1500.0,6.2,1.31,3.0,13.0,2012,2012-01-06
4,1399.0,ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS,GOA,31.0,5.9,7.2,52.0,2.1,0.08,233.0,90.0,2012,2012-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,2052.0,TUIRIAL UPPER CATCHMENT,MIZORAM,23.6,6.9,7.1,186.0,1.6,0.10,233.0,29.0,2014,2014-12-22
734,2053.0,TUIRIAL LOWER CATCHMENT,MIZORAM,23.5,6.8,7.1,201.0,1.4,0.20,233.0,86.0,2014,2014-12-24
735,1403.0,"GUMTI AT U/S SOUTH TRIPURA,TRIPURA",TRIPURA,27.3,6.2,7.8,165.0,2.1,0.00,282.0,340.0,2014,2014-12-25
736,1404.0,"GUMTI AT D/S SOUTH TRIPURA, TRIPURA",TRIPURA,29.1,6.4,7.8,158.0,4.1,0.50,458.0,500.0,2014,2014-12-26
737,1726.0,"CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA",TRIPURA,26.6,6.6,7.9,210.0,4.2,1.90,510.0,572.0,2014,2014-12-27

In [121]:
# Set the 'date' column as the index
data.set_index('date', inplace=True)

# Specify the date you want to find the index for
specified_date = '2012-01-01'

# Get the index of the specified date
index_of_date = data.index.get_loc(specified_date)

print("Index of the specified date '{}' is: {}".format(specified_date, index_of_date))

Index of the specified date '2012-01-01' is: 0

In [78]:
data['date'] = pd.to_datetime(data['date'])
df = data.drop(columns=["STATION CODE", "LOCATIONS", "STATE", "Temp", "year", "date"])
for column in df.columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')

In [79]:
df

,D.O. (mg/l),PH,CONDUCTIVITY (Âµmhos/cm),B.O.D. (mg/l),NITRATENAN N+ NITRITENANN (mg/l),FECAL COLIFORM (MPN/100ml),TOTAL COLIFORM (MPN/100ml)Mean
0,7.1,7.8,151.0,8.0,0.08,233.0,465.0
1,7.2,7.4,319.0,0.7,0.18,5.0,10.0
2,6.2,8.4,894.0,9.0,0.38,140.0,350.0
3,2.4,7.6,1500.0,6.2,1.31,3.0,13.0
4,5.9,7.2,52.0,2.1,0.08,233.0,90.0
...,...,...,...,...,...,...,...
733,6.9,7.1,186.0,1.6,0.10,233.0,29.0
734,6.8,7.1,201.0,1.4,0.20,233.0,86.0
735,6.2,7.8,165.0,2.1,0.00,282.0,340.0
736,6.4,7.8,158.0,4.1,0.50,458.0,500.0
737,6.6,7.9,210.0,4.2,1.90,510.0,572.0

In [80]:
df.fillna(df.median(), inplace=True)
# Checking for outliers
z_scores = df.apply(zscore)
outliers_count = (z_scores.abs() > 3).sum()
df_outliers = np.where(np.abs(z_scores) > 3)[0]
print(outliers_count)
df_filtered = df.drop(df.index[df_outliers])
df_filtered

D.O. (mg/l)                         13
PH                                   2
CONDUCTIVITY (Âµmhos/cm)            26
B.O.D. (mg/l)                       22
NITRATENAN N+ NITRITENANN (mg/l)    15
FECAL COLIFORM (MPN/100ml)          25
TOTAL COLIFORM (MPN/100ml)Mean      28
dtype: int64

,D.O. (mg/l),PH,CONDUCTIVITY (Âµmhos/cm),B.O.D. (mg/l),NITRATENAN N+ NITRITENANN (mg/l),FECAL COLIFORM (MPN/100ml),TOTAL COLIFORM (MPN/100ml)Mean
0,7.1,7.8,151.0,8.0,0.08,233.0,465.0
1,7.2,7.4,319.0,0.7,0.18,5.0,10.0
2,6.2,8.4,894.0,9.0,0.38,140.0,350.0
4,5.9,7.2,52.0,2.1,0.08,233.0,90.0
5,6.1,6.8,408.0,1.3,0.17,1300.0,3808.0
...,...,...,...,...,...,...,...
733,6.9,7.1,186.0,1.6,0.10,233.0,29.0
734,6.8,7.1,201.0,1.4,0.20,233.0,86.0
735,6.2,7.8,165.0,2.1,0.00,282.0,340.0
736,6.4,7.8,158.0,4.1,0.50,458.0,500.0
737,6.6,7.9,210.0,4.2,1.90,510.0,572.0

In [84]:
X = df_filtered.iloc[:,:7].values
print(X)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

[[7.10e+00 7.80e+00 1.51e+02 ... 8.00e-02 2.33e+02 4.65e+02]
 [7.20e+00 7.40e+00 3.19e+02 ... 1.80e-01 5.00e+00 1.00e+01]
 [6.20e+00 8.40e+00 8.94e+02 ... 3.80e-01 1.40e+02 3.50e+02]
 ...
 [6.20e+00 7.80e+00 1.65e+02 ... 0.00e+00 2.82e+02 3.40e+02]
 [6.40e+00 7.80e+00 1.58e+02 ... 5.00e-01 4.58e+02 5.00e+02]
 [6.60e+00 7.90e+00 2.10e+02 ... 1.90e+00 5.10e+02 5.72e+02]]

array([[ 0.42160387,  1.14833701, -0.27730426, ..., -0.76368175,
        -0.29257625, -0.30916859],
       [ 0.53655503,  0.23740822, -0.1056815 , ..., -0.68517274,
        -0.38057367, -0.40615524],
       [-0.61295655,  2.51473018,  0.48171783, ..., -0.52815473,
        -0.32846993, -0.3336817 ],
       ...,
       [-0.61295655,  1.14833701, -0.26300236, ..., -0.82648895,
        -0.27366452, -0.33581327],
       [-0.38305424,  1.14833701, -0.27015331, ..., -0.43394393,
        -0.20573669, -0.30170808],
       [-0.15315192,  1.3760692 , -0.21703198, ...,  0.66518213,
        -0.1856671 , -0.28636074]])

In [65]:
# predict the water quality index based on a set of measurements
def predict_wqi(values):
    import joblib
    model = joblib.load('regressor_model.pkl')
    if(len(values.shape) == 1):
        values = values.reshape(1,-1)
    
    y_pred = model.predict(values)
    
    return y_pred


# determine the water quality class based on a wqi value
# the function takes an array
def get_wqc(wqi):
    import numpy as np
    wqc = []
    wqi = np.array(wqi)
    if(len(wqi.shape) == 0):
        wqi = wqi.reshape(1,-1)
        
    print(wqi)
        
    for i in range(wqi.shape[0]):
        if(wqi[i] <= 50):
            wqc.append("good")
        elif(wqi[i] <= 100):
            wqc.append("poor")
        else:
            wqc.append("unsuitable")
    return np.array(wqc)

In [93]:
X_scaled[1]

array([ 0.53655503,  0.23740822, -0.1056815 , -0.66423783, -0.68517274,
       -0.38057367, -0.40615524])

In [95]:
predict_wqi(X_scaled[1])

c:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator MLPRegressor from version 1.3.0 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

array([19.38327189])

In [92]:
get_wqc(predict_wqi(X_scaled[1]))

[19.38327212]

c:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator MLPRegressor from version 1.3.0 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

array(['good'], dtype='<U4')

In [126]:
data

,STATION CODE,LOCATIONS,STATE,Temp,D.O. (mg/l),PH,CONDUCTIVITY (Âµmhos/cm),B.O.D. (mg/l),NITRATENAN N+ NITRITENANN (mg/l),FECAL COLIFORM (MPN/100ml),TOTAL COLIFORM (MPN/100ml)Mean,year
date,,,,,,,,,,,,
2012-01-01,1393.0,DAMANGANGA AT D/S OF MADHUBAN,DAMAN & DIU,31.0,7.1,7.8,151.0,8.0,0.08,233.0,465.0,2012
2012-01-04,1150.0,DAMANGANGA AT KACHIGAON U\S AT GIDC WIER,GUJARAT,28.0,7.2,7.4,319.0,0.7,0.18,5.0,10.0,2012
2012-01-05,1865.0,RIVER DHADAR AT KOTHADA,GUJARAT,27.0,6.2,8.4,894.0,9.0,0.38,140.0,350.0,2012
2012-01-06,1149.0,KOLAK AT PATALIA BDG,GUJARAT,29.0,2.4,7.6,1500.0,6.2,1.31,3.0,13.0,2012
2012-01-07,1399.0,ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS,GOA,31.0,5.9,7.2,52.0,2.1,0.08,233.0,90.0,2012
...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-22,2052.0,TUIRIAL UPPER CATCHMENT,MIZORAM,23.6,6.9,7.1,186.0,1.6,0.10,233.0,29.0,2014
2014-12-24,2053.0,TUIRIAL LOWER CATCHMENT,MIZORAM,23.5,6.8,7.1,201.0,1.4,0.20,233.0,86.0,2014
2014-12-25,1403.0,"GUMTI AT U/S SOUTH TRIPURA,TRIPURA",TRIPURA,27.3,6.2,7.8,165.0,2.1,0.00,282.0,340.0,2014
2014-12-26,1404.0,"GUMTI AT D/S SOUTH TRIPURA, TRIPURA",TRIPURA,29.1,6.4,7.8,158.0,4.1,0.50,458.0,500.0,2014
2014-12-27,1726.0,"CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA",TRIPURA,26.6,6.6,7.9,210.0,4.2,1.90,510.0,572.0,2014

In [124]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from scipy.stats import zscore

def wqi_gauge(specified_date):
    df = data.copy()
    print(df)
    df['date'] = pd.to_datetime(df['date'])
    df.set_index('date', inplace=True)
    index_of_date = df.index.get_loc(specified_date)
    
    df = df.drop(columns=["STATION CODE", "LOCATIONS", "STATE", "Temp", "year", "date"])
    
    for column in df.columns:
        df[column] = pd.to_numeric(df[column], errors='coerce')
        
    df.fillna(df.median(), inplace=True)
    
    # Checking for outliers in the full dfset
    z_scores = df.apply(zscore)
    outliers_count = (z_scores.abs() > 3).sum()
    df_outliers = np.where(np.abs(z_scores) > 3)[0]
    print(outliers_count)
    df_filtered = df.drop(df.index[df_outliers])
    
    # Scale the df
    scaler = StandardScaler()
    X = df_filtered.values
    X_scaled = scaler.fit_transform(X)
    
    return X_scaled[index_of_date]

In [125]:
wqi_gauge('2012-01-05')

            STATION CODE                                         LOCATIONS  \
date
2012-01-01        1393.0                     DAMANGANGA AT D/S OF MADHUBAN
2012-01-04        1150.0          DAMANGANGA AT KACHIGAON U\S AT GIDC WIER
2012-01-05        1865.0                           RIVER DHADAR AT KOTHADA
2012-01-06        1149.0                              KOLAK AT PATALIA BDG
2012-01-07        1399.0  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS
...                  ...                                               ...
2014-12-22        2052.0                           TUIRIAL UPPER CATCHMENT
2014-12-24        2053.0                           TUIRIAL LOWER CATCHMENT
2014-12-25        1403.0                GUMTI AT U/S SOUTH TRIPURA,TRIPURA
2014-12-26        1404.0               GUMTI AT D/S SOUTH TRIPURA, TRIPURA
2014-12-27        1726.0  CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA

                  STATE  Temp  D.O. (mg/l)   PH  CONDUCTIVITY (Âµmhos/cm)  \
date
2012-01-01  DAMAN & DIU  31.0          7.1  7.8                     151.0
2012-01-04      GUJARAT  28.0          7.2  7.4                     319.0
2012-01-05      GUJARAT  27.0          6.2  8.4                     894.0
2012-01-06      GUJARAT  29.0          2.4  7.6                    1500.0
2012-01-07          GOA  31.0          5.9  7.2                      52.0
...                 ...   ...          ...  ...                       ...
2014-12-22      MIZORAM  23.6          6.9  7.1                     186.0
2014-12-24      MIZORAM  23.5          6.8  7.1                     201.0
2014-12-25      TRIPURA  27.3          6.2  7.8                     165.0
2014-12-26      TRIPURA  29.1          6.4  7.8                     158.0
2014-12-27      TRIPURA  26.6          6.6  7.9                     210.0

            B.O.D. (mg/l)  NITRATENAN N+ NITRITENANN (mg/l)  \
date
2012-01-01            8.0                              0.08
2012-01-04            0.7                              0.18
2012-01-05            9.0                              0.38
2012-01-06            6.2                              1.31
2012-01-07            2.1                              0.08
...                   ...                               ...
2014-12-22            1.6                              0.10
2014-12-24            1.4                              0.20
2014-12-25            2.1                              0.00
2014-12-26            4.1                              0.50
2014-12-27            4.2                              1.90

            FECAL COLIFORM (MPN/100ml)  TOTAL COLIFORM (MPN/100ml)Mean  year
date
2012-01-01                       233.0                           465.0  2012
2012-01-04                         5.0                            10.0  2012
2012-01-05                       140.0                           350.0  2012
2012-01-06                         3.0                            13.0  2012
2012-01-07                       233.0                            90.0  2012
...                                ...                             ...   ...
2014-12-22                       233.0                            29.0  2014
2014-12-24                       233.0                            86.0  2014
2014-12-25                       282.0                           340.0  2014
2014-12-26                       458.0                           500.0  2014
2014-12-27                       510.0                           572.0  2014

[738 rows x 12 columns]

KeyError: 'date'

In [97]:
data = pd.read_csv("../backend/dataset/indian_water_physicochemical_parameters.csv", encoding = 'unicode_escape')
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data

,STATION CODE,LOCATIONS,STATE,Temp,D.O. (mg/l),PH,CONDUCTIVITY (Âµmhos/cm),B.O.D. (mg/l),NITRATENAN N+ NITRITENANN (mg/l),FECAL COLIFORM (MPN/100ml),TOTAL COLIFORM (MPN/100ml)Mean,year,date
0,1393.0,DAMANGANGA AT D/S OF MADHUBAN,DAMAN & DIU,31.0,7.1,7.8,151.0,8.0,0.08,233.0,465.0,2012,2012-01-01
1,1150.0,DAMANGANGA AT KACHIGAON U\S AT GIDC WIER,GUJARAT,28.0,7.2,7.4,319.0,0.7,0.18,5.0,10.0,2012,2012-01-04
2,1865.0,RIVER DHADAR AT KOTHADA,GUJARAT,27.0,6.2,8.4,894.0,9.0,0.38,140.0,350.0,2012,2012-01-05
3,1149.0,KOLAK AT PATALIA BDG,GUJARAT,29.0,2.4,7.6,1500.0,6.2,1.31,3.0,13.0,2012,2012-01-06
4,1399.0,ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS,GOA,31.0,5.9,7.2,52.0,2.1,0.08,233.0,90.0,2012,2012-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,2052.0,TUIRIAL UPPER CATCHMENT,MIZORAM,23.6,6.9,7.1,186.0,1.6,0.10,233.0,29.0,2014,2014-12-22
734,2053.0,TUIRIAL LOWER CATCHMENT,MIZORAM,23.5,6.8,7.1,201.0,1.4,0.20,233.0,86.0,2014,2014-12-24
735,1403.0,"GUMTI AT U/S SOUTH TRIPURA,TRIPURA",TRIPURA,27.3,6.2,7.8,165.0,2.1,0.00,282.0,340.0,2014,2014-12-25
736,1404.0,"GUMTI AT D/S SOUTH TRIPURA, TRIPURA",TRIPURA,29.1,6.4,7.8,158.0,4.1,0.50,458.0,500.0,2014,2014-12-26
737,1726.0,"CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA",TRIPURA,26.6,6.6,7.9,210.0,4.2,1.90,510.0,572.0,2014,2014-12-27

In [98]:
df = data.drop(columns=["STATION CODE", "LOCATIONS", "STATE", "Temp", "year", "date"])

In [99]:
data

,STATION CODE,LOCATIONS,STATE,Temp,D.O. (mg/l),PH,CONDUCTIVITY (Âµmhos/cm),B.O.D. (mg/l),NITRATENAN N+ NITRITENANN (mg/l),FECAL COLIFORM (MPN/100ml),TOTAL COLIFORM (MPN/100ml)Mean,year,date
0,1393.0,DAMANGANGA AT D/S OF MADHUBAN,DAMAN & DIU,31.0,7.1,7.8,151.0,8.0,0.08,233.0,465.0,2012,2012-01-01
1,1150.0,DAMANGANGA AT KACHIGAON U\S AT GIDC WIER,GUJARAT,28.0,7.2,7.4,319.0,0.7,0.18,5.0,10.0,2012,2012-01-04
2,1865.0,RIVER DHADAR AT KOTHADA,GUJARAT,27.0,6.2,8.4,894.0,9.0,0.38,140.0,350.0,2012,2012-01-05
3,1149.0,KOLAK AT PATALIA BDG,GUJARAT,29.0,2.4,7.6,1500.0,6.2,1.31,3.0,13.0,2012,2012-01-06
4,1399.0,ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS,GOA,31.0,5.9,7.2,52.0,2.1,0.08,233.0,90.0,2012,2012-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,2052.0,TUIRIAL UPPER CATCHMENT,MIZORAM,23.6,6.9,7.1,186.0,1.6,0.10,233.0,29.0,2014,2014-12-22
734,2053.0,TUIRIAL LOWER CATCHMENT,MIZORAM,23.5,6.8,7.1,201.0,1.4,0.20,233.0,86.0,2014,2014-12-24
735,1403.0,"GUMTI AT U/S SOUTH TRIPURA,TRIPURA",TRIPURA,27.3,6.2,7.8,165.0,2.1,0.00,282.0,340.0,2014,2014-12-25
736,1404.0,"GUMTI AT D/S SOUTH TRIPURA, TRIPURA",TRIPURA,29.1,6.4,7.8,158.0,4.1,0.50,458.0,500.0,2014,2014-12-26
737,1726.0,"CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA",TRIPURA,26.6,6.6,7.9,210.0,4.2,1.90,510.0,572.0,2014,2014-12-27

In [109]:
import pandas as pd

# Assuming your data is stored in a DataFrame called data

# Convert the 'date' column to datetime format if it's not already in datetime format
data['date'] = pd.to_datetime(data['date'])

# Specify the date you want to extract data for
specified_date = '2012-01-05'  # Change this to your desired date

# Filter the DataFrame to get data for the specified date and create a copy
specified_date_data = data[data['date'] == specified_date].copy()

# Drop the specified columns
specified_date_data.drop(columns=['STATION CODE', 'LOCATIONS', 'STATE', 'Temp', 'year', 'date'], inplace=True)

# Print the modified data for the specified date
print(specified_date_data.values)

[[6.20e+00 8.40e+00 8.94e+02 9.00e+00 3.80e-01 1.40e+02 3.50e+02]]